### ISSUE TITLE
Server gets in a loop on start up when using anything like mohist, magma, and catserver

### ISSUE THREAD

**Issue by SaltyyCoffee** [ValkyrienSkies/Valkyrien-Skies-2#233]
The server gets stuck trying to startup saying

[16:13:46 WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?

But the server never actually finishes loading.

But there are multiple references screaming something about mixin.

[16:13:15 ERROR]: Caught exception in thread Thread[Worker-Main-10,5,main]
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at net.minecraft.world.server.ChunkManager.func_219210_a(ChunkManager.java:1001) ~[?:?]
        at net.minecraft.world.server.ServerChunkProvider.func_217230_c(ServerChunkProvider.java:531) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_217465_m(ServerWorld.java:1248) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_217440_f(ServerWorld.java:1095) ~[?:?]
        at net.minecraft.world.server.ChunkManager.lambda$protoChunkToFullChunk$25(ChunkManager.java:621) ~[?:?]
        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[?:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?]
        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[?:?]
        at net.minecraft.world.server.ChunkManager.func_219193_a_(ChunkManager.java:596) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
        at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(ServerChunkProvider.java:592) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
        at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(ServerChunkProvider.java:600) ~[?:?]
        at net.minecraft.world.server.ServerChunkProvider.func_217234_d(ServerChunkProvider.java:305) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:927) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:916) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeModerately(MinecraftServer.java:895) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213186_a(MinecraftServer.java:520) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:351) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:221) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector includeShips(Lnet/minecraft/world/TrackedEntity;)Lnet/minecraft/util/math/vector/Vector3d; in valkyrienskies-common.mixins.json:server.world.MixinChunkMap$TrackedEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap valkyrienskies-116-common-refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        ... 37 more
        
        

And

[16:13:16 ERROR]: Caught exception in thread Thread[Worker-Main-8,5,main]
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at net.minecraft.world.server.ChunkManager.func_219210_a(ChunkManager.java:1001) ~[?:?]
        at net.minecraft.world.server.ServerChunkProvider.func_217230_c(ServerChunkProvider.java:531) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_217465_m(ServerWorld.java:1248) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_217440_f(ServerWorld.java:1095) ~[?:?]
        at net.minecraft.world.server.ChunkManager.lambda$protoChunkToFullChunk$25(ChunkManager.java:621) ~[?:?]
        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[?:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?]
        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[?:?]
        at net.minecraft.world.server.ChunkManager.func_219193_a_(ChunkManager.java:596) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
        at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(ServerChunkProvider.java:592) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
        at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(ServerChunkProvider.java:600) ~[?:?]
        at net.minecraft.world.server.ServerChunkProvider.func_217234_d(ServerChunkProvider.java:305) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:927) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:916) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeModerately(MinecraftServer.java:895) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213186_a(MinecraftServer.java:520) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:351) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:221) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector includeShips(Lnet/minecraft/world/TrackedEntity;)Lnet/minecraft/util/math/vector/Vector3d; in valkyrienskies-common.mixins.json:server.world.MixinChunkMap$TrackedEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap valkyrienskies-116-common-refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.4.jar:0.8.4+unknown-b0.git-unknown]
        ... 37 more

**Comment by Rubydesic** [comment]
Use arclight
