### ISSUE TITLE
server crashes on start up forge 1.16.5

### ISSUE THREAD

**Issue by Skytress** [ValkyrienSkies/Valkyrien-Skies-2#253]
---- Minecraft Crash Report ----
// Sorry :(

Time: 12/14/22 5:23 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:71) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:37) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37) ~[forge_1.16.5.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49) [forge_1.16.5.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46) [forge_1.16.5.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:43) [forge_1.16.5.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at org.valkyrienskies.core.hooks.VSCoreHooksKt.getCoreHooks(VSCoreHooks.kt:32) ~[valkyrienskies:?] {re:mixin,re:classloading}
-- MOD vs_eureka --
Details:
	Mod File: eureka-1.0.0-alpha6 (1).jar
	Failure message: VS Eureka Mod (vs_eureka) has failed to load correctly
		kotlin.UninitializedPropertyAccessException: lateinit property CoreHooks has not been initialized
	Mod Version: 1.0.0-alpha6
	Mod Issue URL: https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues
	Exception message: kotlin.UninitializedPropertyAccessException: lateinit property CoreHooks has not been initialized
Stacktrace:
	at org.valkyrienskies.core.hooks.VSCoreHooksKt.getCoreHooks(VSCoreHooks.kt:32) ~[valkyrienskies:?] {re:mixin,re:classloading}
	at org.valkyrienskies.core.config.VSConfigClass.readOrCreateConfig(VSConfigClass.kt:59) ~[valkyrienskies:?] {re:classloading}
	at org.valkyrienskies.core.config.VSConfigClass$Companion.registerConfig(VSConfigClass.kt:260) ~[valkyrienskies:?] {re:classloading}
	at org.valkyrienskies.eureka.EurekaMod.init(EurekaMod.java:20) ~[vs_eureka:?] {re:classloading}
	at org.valkyrienskies.eureka.forge.EurekaModForge.<init>(EurekaModForge.java:43) ~[vs_eureka:?] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_312] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_312] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_312] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_312] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_312] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_312] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_312] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_312] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_312] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_312] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_312] {}

**Comment by Rubydesic** [comment]
fixed in latest eureka
