### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION when attempting to place a shaft from the Create mod on a ship

### ISSUE THREAD

**Issue by klebin-bit** [ValkyrienSkies/Valkyrien-Skies-2#284]
Also this is in logs when trying to assemble a ship with only a shaft:
```
[16:42:38] [Render thread/INFO] [minecraft/ChatComponent]: [CHAT] SHIPIFIED!
[16:42:38] [Server thread/WARN] [or.va.co.im.ne.NetworkChannel/]: Ship with ID 11 has a mass of 0.0, not creating a ShipObject
[16:42:38] [Server thread/WARN] [or.va.co.im.ne.NetworkChannel/]: Ship with ID 11 has a mass of 0.0, not creating a ShipObject
[16:42:38] [Physics thread/ERROR] [or.va.co.im.pi.VSPhysicsPipelineBackgroundTask/]: Error in physics pipeline background task
java.lang.IllegalStateException: Tried sending voxel updates to rigid body from ship with UUID 11, but no rigid body exists for this ship!
	at org.valkyrienskies.core.impl.pipelines.VSPhysicsPipelineStage.applyGameFrame(VSPhysicsPipelineStage.kt:194) ~[valkyrienskies-118-2.1.0-beta7.jar%2356!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.pipelines.VSPhysicsPipelineStage.tickPhysics(VSPhysicsPipelineStage.kt:77) ~[valkyrienskies-118-2.1.0-beta7.jar%2356!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.pipelines.VSPipelineImpl.tickPhysics(VSPipelineImpl.kt:109) ~[valkyrienskies-118-2.1.0-beta7.jar%2356!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.pipelines.VSPhysicsPipelineBackgroundTask.run(VSPhysicsPipelineBackgroundTask.kt:75) [valkyrienskies-118-2.1.0-beta7.jar%2356!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.pipelines.VSPipelineImpl$physicsThread$1.invoke(VSPipelineImpl.kt:65) [valkyrienskies-118-2.1.0-beta7.jar%2356!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.pipelines.VSPipelineImpl$physicsThread$1.invoke(VSPipelineImpl.kt:64) [valkyrienskies-118-2.1.0-beta7.jar%2356!/:?] {re:classloading}
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) [kotlinforforge-3.8.0-obf.jar%2355!/:3.8.0] {}
[16:42:38] [Physics thread/ERROR] [or.va.co.im.pi.VSPhysicsPipelineBackgroundTask/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[16:42:38] [Physics thread/ERROR] [or.va.co.im.pi.VSPhysicsPipelineBackgroundTask/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[16:42:38] [Physics thread/ERROR] [or.va.co.im.pi.VSPhysicsPipelineBackgroundTask/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[16:42:38] [Physics thread/ERROR] [or.va.co.im.pi.VSPhysicsPipelineBackgroundTask/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[16:42:38] [Physics thread/ERROR] [or.va.co.im.pi.VSPhysicsPipelineBackgroundTask/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[16:42:38] [Physics thread/ERROR] [or.va.co.im.pi.VSPhysicsPipelineBackgroundTask/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[16:42:38] [Physics thread/ERROR] [or.va.co.im.pi.VSPhysicsPipelineBackgroundTask/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[16:42:38] [Physics thread/ERROR] [or.va.co.im.pi.VSPhysicsPipelineBackgroundTask/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[16:42:38] [Physics thread/ERROR] [or.va.co.im.pi.VSPhysicsPipelineBackgroundTask/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[16:42:38] [Physics thread/ERROR] [or.va.co.im.pi.VSPhysicsPipelineBackgroundTask/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[16:42:38] [Physics thread/WARN] [or.va.co.im.pi.VSPhysicsPipelineBackgroundTask/]: Physics pipeline ending
[16:42:38] [Server thread/WARN] [or.va.co.im.ne.NetworkChannel/]: Ship with ID 11 has a mass of 0.0, not creating a ShipObject
[16:42:38] [Server thread/WARN] [or.va.co.im.ne.NetworkChannel/]: Ship with ID 11 has a mass of 0.0, not creating a ShipObject
[16:42:38] [Server thread/WARN] [or.va.co.im.ne.NetworkChannel/]: Ship with ID 11 has a mass of 0.0, not creating a ShipObject
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb17f0eba0, pid=16688, tid=2588
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.4+8 (17.0.4+8) (build 17.0.4+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (17.0.4+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [nvoglv64.dll+0x14ceba0]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Minecraft\multimc\instances\the closest i can get to aeronautics before aeronautics\.minecraft\hs_err_pid16688.log
[16:42:38] [Server thread/WARN] [or.va.co.im.ne.NetworkChannel/]: Ship with ID 11 has a mass of 0.0, not creating a ShipObject
[16:42:38] [Server thread/WARN] [or.va.co.im.ne.NetworkChannel/]: Ship with ID 11 has a mass of 0.0, not creating a ShipObject
[16:42:38] [Server thread/WARN] [or.va.co.im.ne.NetworkChannel/]: Ship with ID 11 has a mass of 0.0, not creating a ShipObject
[16:42:38] [Server thread/WARN] [or.va.co.im.ne.NetworkChannel/]: Ship with ID 11 has a mass of 0.0, not creating a ShipObject
[16:42:38] [Server thread/WARN] [or.va.co.im.ne.NetworkChannel/]: Ship with ID 11 has a mass of 0.0, not creating a ShipObject
[16:42:38] [Server thread/WARN] [or.va.co.im.ne.NetworkChannel/]: Ship with ID 11 has a mass of 0.0, not creating a ShipObject
[16:42:38] [Server thread/WARN] [or.va.co.im.ne.NetworkChannel/]: Ship with ID 11 has a mass of 0.0, not creating a ShipObject
[16:42:38] [Server thread/WARN] [or.va.co.im.ne.NetworkChannel/]: Ship with ID 11 has a mass of 0.0, not creating a ShipObject
[16:42:38] [Server thread/WARN] [or.va.co.im.ne.NetworkChannel/]: Ship with ID 11 has a mass of 0.0, not creating a ShipObject
[16:42:38] [Server thread/WARN] [or.va.co.im.ne.NetworkChannel/]: Ship with ID 11 has a mass of 0.0, not creating a ShipObject
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
```

What I have tried:
Changing the forge version

**Comment by ThePlasticPotato** [comment]
Is it create 0.5G?

**Comment by klebin-bit** [comment]
> Is it create 0.5G?

It is.

**Comment by ThePlasticPotato** [comment]
Incompatible, use 0.5e until it’s fixed. They redid their rendering stuff and all the mixins done broke.
