### ISSUE TITLE
Exception stopping the server with Valkryien skies2 [forge1.18.2]

### ISSUE THREAD

**Issue by Xplodin** [ValkyrienSkies/Valkyrien-Skies-2#364]
[16:07:36] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "org.valkyrienskies.core.apigame.world.ServerShipWorldCore.onDisconnect(org.valkyrienskies.core.apigame.world.IPlayer)" because the return value of "org.valkyrienskies.mod.common.VSGameUtilsKt.getShipObjectWorld(net.minecraft.server.MinecraftServer)" is null
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handler$znf000$onDisconnect(ServerGamePacketListenerImpl.java:2666) ~[server-1.18.2-20220404.173914-srg.jar%23440!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7026_(ServerGamePacketListenerImpl.java) ~[server-1.18.2-20220404.173914-srg.jar%23440!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.network.Connection.m_129541_(Connection.java:394) ~[server-1.18.2-20220404.173914-srg.jar%23440!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:NetworkManagerMixin,pl:mixin:APP:connectivity.mixins.json:ConnectionErrorMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_18709_(BlockableEventLoop.java:88) ~[server-1.18.2-20220404.173914-srg.jar%23440!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9942_(ServerGamePacketListenerImpl.java:296) ~[server-1.18.2-20220404.173914-srg.jar%23440!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.players.PlayerList.m_11313_(PlayerList.java:715) ~[server-1.18.2-20220404.173914-srg.jar%23440!/:?] {re:mixin,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:PlayerListMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinPlayerList,pl:mixin:APP:enhancedcelestials.mixins.json:MixinPlayerList,pl:mixin:APP:mixins.dcintegration.json:MixinPlayerLogin,pl:mixin:APP:pehkui.mixins.json:PlayerManagerMixin,pl:mixin:APP:byg.mixins.json:common.MixinPlayerList,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinPlayerList,pl:mixin:APP:securitycraft.mixins.json:camera.PlayerListMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.PlayerListMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:585) ~[server-1.18.2-20220404.173914-srg.jar%23440!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_7041_(DedicatedServer.java:543) ~[server-1.18.2-20220404.173914-srg.jar%23440!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:717) ~[server-1.18.2-20220404.173914-srg.jar%23440!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23440!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

**Comment by Rubydesic** [comment]
should be fixed in latest
