### ISSUE TITLE
Error in Server Network Thread - possible mod incompatibility on server

### ISSUE THREAD

**Issue by RobAllen0** [ValkyrienSkies/Valkyrien-Skies-2#399]
Getting a bunch of server spam like this:
`
[29.01 20:46:21] [Server] java.lang.IllegalArgumentExceptionvalue already present: org.valkyrienskies.mod.common.util.MinecraftPlayer@287550d7
[29.01 20:46:21] [Server] 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[29.01 20:46:21] [Server] 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[29.01 20:46:21] [Server] 	at org.valkyrienskies.core.networking.UdpServerImpl.run(UdpServerImpl.kt:77) ~[valkyrienskies:?] {re:classloading}
[29.01 20:46:21] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_{}
[29.01 20:46:26] [Server] [Thread-45/ERROR] [or.va.co.ne.UdpServerImpl/]: Error in server network thread
[29.01 20:46:26] [Server] java.lang.IllegalArgumentExceptionvalue already present: org.valkyrienskies.mod.common.util.MinecraftPlayer@287550d7
[29.01 20:46:26] [Server] 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[29.01 20:46:26] [Server] 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[29.01 20:46:26] [Server] 	at org.valkyrienskies.core.networking.UdpServerImpl.run(UdpServerImpl.kt:77) ~[valkyrienskies:?] {re:classloading}
[29.01 20:46:26] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_{}
[29.01 20:46:31] [Server] [Thread-45/ERROR] [or.va.co.ne.UdpServerImpl/]: Error in server network thread
[29.01 20:46:31] [Server] java.lang.IllegalArgumentExceptionvalue already present: org.valkyrienskies.mod.common.util.MinecraftPlayer@287550d7
[29.01 20:46:31] [Server] 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[29.01 20:46:31] [Server] 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[29.01 20:46:31] [Server] 	at org.valkyrienskies.core.networking.UdpServerImpl.run(UdpServerImpl.kt:77) ~[valkyrienskies:?] {re:classloading}
[29.01 20:46:31] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_{}
[29.01 20:46:36] [Server] [Thread-45/ERROR] [or.va.co.ne.UdpServerImpl/]: Error in server network thread
[29.01 20:46:36] [Server] java.lang.IllegalArgumentExceptionvalue already present: org.valkyrienskies.mod.common.util.MinecraftPlayer@287550d7
[29.01 20:46:36] [Server] 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[29.01 20:46:36] [Server] 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[29.01 20:46:36] [Server] 	at org.valkyrienskies.core.networking.UdpServerImpl.run(UdpServerImpl.kt:77) ~[valkyrienskies:?] {re:classloading}
[29.01 20:46:36] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_{}
[29.01 20:46:41] [Server] [Thread-45/ERROR] [or.va.co.ne.UdpServerImpl/]: Error in server network thread
[29.01 20:46:41] [Server] java.lang.IllegalArgumentExceptionvalue already present: org.valkyrienskies.mod.common.util.MinecraftPlayer@287550d7
[29.01 20:46:41] [Server] 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[29.01 20:46:41] [Server] 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[29.01 20:46:41] [Server] 	at org.valkyrienskies.core.networking.UdpServerImpl.run(UdpServerImpl.kt:77) ~[valkyrienskies:?] {re:classloading}
[29.01 20:46:41] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_{}
`

Modpack is Beyond Arcadia on Curseforge: https://www.curseforge.com/minecraft/modpacks/beyond-arcadia

I'd like to identify which mod might be causing the issue (if it is a compatibility issue at all).  Preferably something can be done to resolve the issue, but if necessary I am prepared to remove the offending mod as I'd rather keep VS2.

**Comment by Rubydesic** [comment]
Disable UDP in config
