### ISSUE TITLE
Can't register commands serverside [Magma 1.18.2]

### ISSUE THREAD

**Issue by Proxwian** [ValkyrienSkies/Valkyrien-Skies-2#467]
[01May2023 22:02:01.867] [main/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Collection contains no element matching the predicate.
	Index: 77
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@383d3a2f
		4: ASM: class net.lavabucket.hourglass.command.HourglassCommand onRegisterCommandEvent(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		5: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@649eb5a2
		6: ASM: class com.dynamic_view.event.EventHandler onCommandsRegister(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		7: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@28c11e22
		8: ASM: net.flytre.flytre_lib.ForgeEventBus@627e5ee registerCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		9: ASM: jeresources.profiling.ProfileCommand@59736c0b registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		10: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@6a9ad80c
		11: ASM: class net.mcreator.trysurvive.command.InfectStrokeCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		12: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@3b277b32
		13: ASM: class net.mcreator.trysurvive.command.InfectScorchCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		14: ASM: class net.mcreator.trysurvive.command.InfectRabiesCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		15: ASM: class net.mcreator.trysurvive.command.InfectPneumoniaCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		16: ASM: class net.mcreator.trysurvive.command.InfectParasitesCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		17: ASM: class net.mcreator.trysurvive.command.InfectNecrosisCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		18: ASM: class net.mcreator.trysurvive.command.InfectIndigestionCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		19: ASM: class net.mcreator.trysurvive.command.InfectFluCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		20: ASM: class net.mcreator.trysurvive.command.InfectFeverCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		21: ASM: class net.mcreator.trysurvive.command.InfectColdCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		22: ASM: class net.mcreator.trysurvive.command.HelpTotalImmunityCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		23: ASM: class net.mcreator.trysurvive.command.HelpStrokeCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		24: ASM: class net.mcreator.trysurvive.command.HelpSevereBurnsCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		25: ASM: class net.mcreator.trysurvive.command.HelpScorchCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		26: ASM: class net.mcreator.trysurvive.command.HelpSatiationCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		27: ASM: class net.mcreator.trysurvive.command.HelpRabiesCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		28: ASM: class net.mcreator.trysurvive.command.HelpPneumoniaCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		29: ASM: class net.mcreator.trysurvive.command.HelpParasitesCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		30: ASM: class net.mcreator.trysurvive.command.HelpNetherProtectionCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		31: ASM: class net.mcreator.trysurvive.command.HelpNecrosisCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		32: ASM: class net.mcreator.trysurvive.command.HelpIndigestionCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		33: ASM: class net.mcreator.trysurvive.command.HelpImmunizedCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		34: ASM: class net.mcreator.trysurvive.command.HelpFreezingOfTheVoidCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		35: ASM: class net.mcreator.trysurvive.command.HelpFluCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		36: ASM: class net.mcreator.trysurvive.command.HelpFeverCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		37: ASM: class net.mcreator.trysurvive.command.HelpDrovwnedCanDrownCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		38: ASM: class net.mcreator.trysurvive.command.HelpDeepWoundsCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		39: ASM: class net.mcreator.trysurvive.command.HelpColdCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		40: ASM: class net.mcreator.trysurvive.command.HelpBurningAirOfHellCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		41: ASM: class net.mcreator.trysurvive.command.CheckTotalImmunityCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		42: ASM: class net.mcreator.trysurvive.command.CheckSurvivalMasterCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		43: ASM: class me.maxish0t.wac.common.init.RegisterCommandEvent onRegisterCommandEvent(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		44: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@2a05ea51
		45: ASM: insane96mcp.enhancedai.EnhancedAI@41b0eb77 registerCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		46: ASM: class sereneseasons.command.SeasonCommands onCommandsRegistered(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		47: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@a15d13d
		48: ASM: class ovh.corail.tombstone.event.EventHandler onRegisterCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		49: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@36f332cb
		50: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@360d31cc
		51: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@335f123e
		52: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@1767a151
		53: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@382dac1c
		54: ASM: class top.seraphjack.simplelogin.command.CommandLoader commandRegister(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		55: ASM: class com.performant.coremod.event.ForgeBusEventHandler onCommandsRegister(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		56: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@67717984
		57: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@2cf449b6
		58: ASM: dev.momostudios.coldsweat.ColdSweat@6b11abc registerCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		59: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@6b31850
		60: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@53ab09d6
		61: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@3f7af77e
		62: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@31cda0de
		63: ASM: class com.sammy.ortus.setup.OrtusCommands registerCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		64: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@2fa25f2f
		65: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@24cc16b4
		66: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@4c65d454
		67: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@10724656
		68: ASM: net.minecraftforge.common.ForgeInternalHandler@44b78108 onCommandsRegister(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		69: ASM: uk.me.joeclack.dimensionalworldborder.DimensionalWorldBorder@400840a0 onRegisterCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		70: ASM: class net.mcreator.supernatural.command.VampireCurseCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		71: ASM: class net.mcreator.supernatural.command.VampireCureCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		72: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler commandRegister(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		73: ASM: class alternate.current.AlternateCurrentMod$ModEvents onRegisterCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		74: ASM: class inzhefop.mekanismmatter.command.MekansimmatterCMDCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		75: ASM: class inzhefop.mekanismmatter.command.GetReplicaValuesCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		76: ASM: class inzhefop.mekanismmatter.command.GetItemIdCommand registerCommand(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		77: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@2d942850
		78: ASM: class gg.moonflower.pollen.core.forge.PollenCommonForgeEvents onEvent(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		79: ASM: class com.blamejared.crafttweaker.impl.event.CTCommonEventHandler registerCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		80: ASM: class sonar.fluxnetworks.register.EventHandler onRegisterCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		81: ASM: com.corosus.modconfig.EventHandlerForge@1c6b57fb registerCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		82: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@69a9e2e0
		83: ASM: com.mrh0.createaddition.CreateAddition@164ac714 onRegisterCommandEvent(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		84: ASM: class net.mehvahdjukaar.supplementaries.setup.ModSetup registerCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		85: ASM: class com.simibubi.create.events.CommonEvents registerCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		86: ASM: mcjty.theoneprobe.ForgeEventHandlers@1b374900 registerCommands(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		87: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@b0c5cf5
		88: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@94eeb34
		89: ASM: mcjty.fxcontrol.ForgeEventHandlers@5e98deaa serverLoad(Lnet/minecraftforge/event/RegisterCommandsEvent;)V
		90: net.minecraftforge.eventbus.EventBus$$Lambda$4358/0x0000000801a5cca8@51494e5
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at TRANSFORMER/valkyrienskies@2.1.0-beta.11/org.valkyrienskies.mod.common.command.VSCommands.registerServerCommands(VSCommands.java:170)
	at TRANSFORMER/valkyrienskies@2.1.0-beta.11/org.valkyrienskies.mod.forge.common.ValkyrienSkiesModForge.registerCommands(ValkyrienSkiesModForge.kt:158)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.2.1/net.minecraftforge.event.ForgeEventFactory.onCommandRegister(ForgeEventFactory.java:749)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.commands.Commands.<init>(Commands.java:137)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.ReloadableServerResources.<init>(ReloadableServerResources.java:41)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.ReloadableServerResources.m_206861_(ReloadableServerResources.java:82)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.WorldStem.m_206911_(WorldStem.java:44)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.1/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at org.magmafoundation.magma.utils.BootstrapLauncher.startServer(BootstrapLauncher.java:96)
	at org.magmafoundation.magma.MagmaStart.main(MagmaStart.java:91)

[01May2023 22:02:01.868] [main/WARN] [net.minecraft.server.Main/]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:266) ~[server-1.18.2-20220404.173914-srg.jar%23304!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.2.1.jar%2331!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at org.magmafoundation.magma.utils.BootstrapLauncher.startServer(BootstrapLauncher.java:96) [Magma-1.18.2.jar:?]
	at org.magmafoundation.magma.MagmaStart.main(MagmaStart.java:91) [Magma-1.18.2.jar:1.18.2-40.2.1-5c167188-20220404.173914]
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at org.valkyrienskies.mod.common.command.VSCommands.registerServerCommands(VSCommands.java:170) ~[valkyrienskies-118-2.1.0-beta.11.jar%23291!/:?]
	at org.valkyrienskies.mod.forge.common.ValkyrienSkiesModForge.registerCommands(ValkyrienSkiesModForge.kt:158) ~[valkyrienskies-118-2.1.0-beta.11.jar%23291!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onCommandRegister(ForgeEventFactory.java:749) ~[forge-1.18.2-40.2.1-universal.jar%23309!/:?]
	at net.minecraft.commands.Commands.<init>(Commands.java:137) ~[server-1.18.2-20220404.173914-srg.jar%23304!/:?]
	at net.minecraft.server.ReloadableServerResources.<init>(ReloadableServerResources.java:41) ~[server-1.18.2-20220404.173914-srg.jar%23304!/:?]
	at net.minecraft.server.ReloadableServerResources.m_206861_(ReloadableServerResources.java:82) ~[server-1.18.2-20220404.173914-srg.jar%23304!/:?]
	at net.minecraft.server.WorldStem.m_206911_(WorldStem.java:44) ~[server-1.18.2-20220404.173914-srg.jar%23304!/:?]
	at net.minecraft.server.Main.main(Main.java:238) ~[server-1.18.2-20220404.173914-srg.jar%23304!/:?]
	... 14 more

**Comment by Rubydesic** [comment]
VS2 generally doesn't support forge/bukkit hybrid servers, but some users have had success with [Arclight](https://github.com/IzzelAliz/Arclight)

**Comment by artegoser** [comment]
Are there plans to add support for such servers in the future?
