### ISSUE TITLE
[1.18.2] 2.1.0 Beta 11 don't know what happened

### ISSUE THREAD

**Issue by Evander0** [ValkyrienSkies/Valkyrien-Skies-2#468]
[22:59:33] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
[22:59:34] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/MC/minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[22:59:34] [main/INFO]: Found mod file valkyrienskies-118-2.1.0-beta.11.jar of type MOD with provider {mods folder locator at D:\MC\minecraft\versions\1.18.2 clockwork\mods}
[22:59:34] [main/WARN]: Mod file D:\MC\minecraft\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.2\fmlcore-1.18.2-40.2.2.jar is missing mods.toml file
[22:59:34] [main/WARN]: Mod file D:\MC\minecraft\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.2.2\javafmllanguage-1.18.2-40.2.2.jar is missing mods.toml file
[22:59:34] [main/WARN]: Mod file D:\MC\minecraft\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.2.2\lowcodelanguage-1.18.2-40.2.2.jar is missing mods.toml file
[22:59:34] [main/WARN]: Mod file D:\MC\minecraft\libraries\net\minecraftforge\mclanguage\1.18.2-40.2.2\mclanguage-1.18.2-40.2.2.jar is missing mods.toml file
[22:59:34] [main/INFO]: Found mod file fmlcore-1.18.2-40.2.2.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3f3ddbd9
[22:59:34] [main/INFO]: Found mod file javafmllanguage-1.18.2-40.2.2.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3f3ddbd9
[22:59:34] [main/INFO]: Found mod file lowcodelanguage-1.18.2-40.2.2.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3f3ddbd9
[22:59:34] [main/INFO]: Found mod file mclanguage-1.18.2-40.2.2.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3f3ddbd9
[22:59:34] [main/INFO]: Found mod file client-1.18.2-20220404.173914-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3f3ddbd9
[22:59:34] [main/INFO]: Found mod file forge-1.18.2-40.2.2-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3f3ddbd9
[22:59:34] [main/INFO]: Found 23 dependencies adding them to mods collection
[22:59:34] [main/INFO]: Found mod file classmate-1.5.1.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file joml-primitives-1.10.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file json-schema-validator-1.0.71.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file jackson-module-parameter-names-2.14.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file jsonschema-module-jackson-4.25.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file jackson-kotlin-dsl-1.2.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file itu-1.7.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file jackson-core-2.14.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file zjsonpatch-0.4.11.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file jackson-databind-2.14.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file jackson-dataformat-cbor-2.14.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file api-1.1.0+4e7914ba1f.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file javax.inject-1.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file jackson-annotations-2.14.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file jackson-module-kotlin-2.14.0-rubyfork.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file jsonschema-generator-4.25.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file MixinExtras-0.1.1.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file dagger-2.43.2.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file jsonschema-module-addon-1.2.1.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file commons-math3-3.6.1.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file cloth-config-forge-6.3.81.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file joml-1.10.4.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:34] [main/INFO]: Found mod file commons-collections4-4.3.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@5ee34b1b
[22:59:36] [main/WARN]: Error loading class: rbasamoyai/createbigcannons/munitions/AbstractCannonProjectile (java.lang.ClassNotFoundException: rbasamoyai.createbigcannons.munitions.AbstractCannonProjectile)
[22:59:36] [main/WARN]: Error loading class: rbasamoyai/createbigcannons/cannon_control/contraption/PitchOrientedContraptionEntity (java.lang.ClassNotFoundException: rbasamoyai.createbigcannons.cannon_control.contraption.PitchOrientedContraptionEntity)
[22:59:36] [main/WARN]: Error loading class: dev/ftb/mods/ftbchunks/data/ClaimedChunkManager (java.lang.ClassNotFoundException: dev.ftb.mods.ftbchunks.data.ClaimedChunkManager)
[22:59:36] [main/WARN]: Error loading class: com/jozufozu/flywheel/backend/instancing/instancing/InstancingEngine (java.lang.ClassNotFoundException: com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine)
[22:59:36] [main/WARN]: Error loading class: com/jozufozu/flywheel/backend/instancing/blockentity/BlockEntityInstanceManager (java.lang.ClassNotFoundException: com.jozufozu.flywheel.backend.instancing.blockentity.BlockEntityInstanceManager)
[22:59:36] [main/WARN]: Error loading class: com/jozufozu/flywheel/backend/instancing/InstanceManager (java.lang.ClassNotFoundException: com.jozufozu.flywheel.backend.instancing.InstanceManager)
[22:59:36] [main/WARN]: Error loading class: com/jozufozu/flywheel/backend/instancing/InstanceWorld (java.lang.ClassNotFoundException: com.jozufozu.flywheel.backend.instancing.InstanceWorld)
[22:59:36] [main/WARN]: Error loading class: com/jozufozu/flywheel/backend/instancing/instancing/InstancingEngine (java.lang.ClassNotFoundException: com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine)
[22:59:36] [main/WARN]: Error loading class: com/sonicether/soundphysics/SoundPhysics (java.lang.ClassNotFoundException: com.sonicether.soundphysics.SoundPhysics)
[22:59:36] [main/WARN]: Error loading class: dan200/computercraft/shared/peripheral/speaker/SpeakerPosition (java.lang.ClassNotFoundException: dan200.computercraft.shared.peripheral.speaker.SpeakerPosition)
[22:59:36] [main/WARN]: Error loading class: dan200/computercraft/shared/turtle/core/TurtleBrain (java.lang.ClassNotFoundException: dan200.computercraft.shared.turtle.core.TurtleBrain)
[22:59:36] [main/WARN]: Error loading class: dan200/computercraft/shared/turtle/core/TurtleMoveCommand (java.lang.ClassNotFoundException: dan200.computercraft.shared.turtle.core.TurtleMoveCommand)
[22:59:36] [main/WARN]: Error loading class: dan200/computercraft/shared/peripheral/modem/wireless/WirelessNetwork (java.lang.ClassNotFoundException: dan200.computercraft.shared.peripheral.modem.wireless.WirelessNetwork)
[22:59:36] [main/WARN]: Error loading class: com/simibubi/create/foundation/collision/Matrix3d (java.lang.ClassNotFoundException: com.simibubi.create.foundation.collision.Matrix3d)
[22:59:36] [main/WARN]: @Mixin target com.simibubi.create.foundation.collision.Matrix3d was not found valkyrienskies-forge.mixins.json:compat.create.Matrix3dAccessor
[22:59:36] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/components/structureMovement/AbstractContraptionEntity (java.lang.ClassNotFoundException: com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity)
[22:59:36] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity was not found valkyrienskies-forge.mixins.json:compat.create.MixinAbstractContraptionEntity
[22:59:36] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/components/actors/BlockBreakingKineticTileEntity (java.lang.ClassNotFoundException: com.simibubi.create.content.contraptions.components.actors.BlockBreakingKineticTileEntity)
[22:59:36] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.components.actors.BlockBreakingKineticTileEntity was not found valkyrienskies-forge.mixins.json:compat.create.MixinBlockBreakingKineticTileEntity
[22:59:36] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/components/millstone/MillstoneBlock (java.lang.ClassNotFoundException: com.simibubi.create.content.contraptions.components.millstone.MillstoneBlock)
[22:59:36] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.components.millstone.MillstoneBlock was not found valkyrienskies-forge.mixins.json:compat.create.MixinBlocks
[22:59:36] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/processing/BasinBlock (java.lang.ClassNotFoundException: com.simibubi.create.content.contraptions.processing.BasinBlock)
[22:59:36] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.processing.BasinBlock was not found valkyrienskies-forge.mixins.json:compat.create.MixinBlocks
[22:59:36] [main/WARN]: Error loading class: com/simibubi/create/content/logistics/block/chute/AbstractChuteBlock (java.lang.ClassNotFoundException: com.simibubi.create.content.logistics.block.chute.AbstractChuteBlock)
[22:59:36] [main/WARN]: @Mixin target com.simibubi.create.content.logistics.block.chute.AbstractChuteBlock was not found valkyrienskies-forge.mixins.json:compat.create.MixinBlocks
[22:59:36] [main/WARN]: Error loading class: blusunrize/immersiveengineering/common/gui/BlockEntityInventory (java.lang.ClassNotFoundException: blusunrize.immersiveengineering.common.gui.BlockEntityInventory)
[22:59:36] [main/WARN]: Error loading class: cofh/core/block/entity/TileCoFH (java.lang.ClassNotFoundException: cofh.core.block.entity.TileCoFH)
[22:59:36] [main/WARN]: Error loading class: li/cil/tis3d/common/entity/InfraredPacketEntity (java.lang.ClassNotFoundException: li.cil.tis3d.common.entity.InfraredPacketEntity)
[22:59:36] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/components/structureMovement/render/ContraptionRenderInfo (java.lang.ClassNotFoundException: com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderInfo)
[22:59:36] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderInfo was not found valkyrienskies-forge.mixins.json:compat.create.client.MixinContraptionRenderInfo
[22:59:36] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/components/structureMovement/render/FlwContraption (java.lang.ClassNotFoundException: com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraption)
[22:59:36] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraption was not found valkyrienskies-forge.mixins.json:compat.create.client.MixinFlwContraption
[22:59:36] [main/WARN]: Error loading class: com/simibubi/create/foundation/tileEntity/behaviour/scrollvalue/ScrollValueBehaviour (java.lang.ClassNotFoundException: com.simibubi.create.foundation.tileEntity.behaviour.scrollvalue.ScrollValueBehaviour)
[22:59:36] [main/WARN]: @Mixin target com.simibubi.create.foundation.tileEntity.behaviour.scrollvalue.ScrollValueBehaviour was not found valkyrienskies-forge.mixins.json:compat.create.client.MixinScrollValueBehaviour
[22:59:36] [main/WARN]: Error loading class: com/simibubi/create/foundation/tileEntity/behaviour/ValueBox (java.lang.ClassNotFoundException: com.simibubi.create.foundation.tileEntity.behaviour.ValueBox)
[22:59:36] [main/WARN]: @Mixin target com.simibubi.create.foundation.tileEntity.behaviour.ValueBox was not found valkyrienskies-forge.mixins.json:compat.create.client.MixinValueBox
[22:59:36] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/RenderSectionManager (java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager)
[22:59:36] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager was not found valkyrienskies-forge.mixins.json:compat.sodium.MixinRenderSectionManager
[22:59:36] [main/WARN]: Error loading class: li/cil/tis3d/client/renderer/tileentity/CasingTileEntityRenderer (java.lang.ClassNotFoundException: li.cil.tis3d.client.renderer.tileentity.CasingTileEntityRenderer)
[22:59:36] [main/WARN]: Error loading class: li/cil/tis3d/client/renderer/RenderContextImpl (java.lang.ClassNotFoundException: li.cil.tis3d.client.renderer.RenderContextImpl)
[22:59:39] [pool-3-thread-1/WARN]: Error loading class: kotlin/jvm/functions/Function0 (java.lang.ClassNotFoundException: kotlin.jvm.functions.Function0)
[22:59:39] [pool-3-thread-1/INFO]: Instancing error handler class org.valkyrienskies.mod.mixin.ValkyrienMixinErrorHandler
[22:59:39] [pool-3-thread-1/FATAL]: Mixin apply failed valkyrienskies-common.mixins.json:feature.block_placement_orientation.MixinBlockPlaceContext -> net.minecraft.world.item.context.BlockPlaceContext: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> valkyrienskies-common.mixins.json:feature.block_placement_orientation.MixinBlockPlaceContext -> Apply Methods -> (Lnet/minecraft/world/entity/Entity;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)[Lnet/minecraft/core/Direction;:wrapOperation$zzf000$transformPlayerBeforeGettingNearest -> Transform Instructions -> INVOKEDYNAMIC invoke (Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;Lnet/minecraft/world/entity/Entity;)Lkotlin/jvm/functions/Function0; -> desc=Lkotlin/jvm/functions/Function0;]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> valkyrienskies-common.mixins.json:feature.block_placement_orientation.MixinBlockPlaceContext -> Apply Methods -> (Lnet/minecraft/world/entity/Entity;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)[Lnet/minecraft/core/Direction;:wrapOperation$zzf000$transformPlayerBeforeGettingNearest -> Transform Instructions -> INVOKEDYNAMIC invoke (Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;Lnet/minecraft/world/entity/Entity;)Lkotlin/jvm/functions/Function0; -> desc=Lkotlin/jvm/functions/Function0;]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:491) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:532) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:518) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:386) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.3.jar:9.1.3+9.1.3+main.9b69c82a]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.entity.EntityType.<clinit>(EntityType.java:183) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.level.levelgen.feature.MonsterRoomFeature.<clinit>(MonsterRoomFeature.java:26) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.level.levelgen.feature.Feature.<clinit>(Feature.java:80) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.data.worldgen.features.AquaticFeatures.<clinit>(AquaticFeatures.java:20) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.data.worldgen.features.FeatureUtils.m_206469_(FeatureUtils.java:23) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.data.BuiltinRegistries.m_206392_(BuiltinRegistries.java:101) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:100) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:633) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:138) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: kotlin.jvm.functions.Function0
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:983) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:943) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethodDescriptor(MixinTargetContext.java:1000) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformInvokeDynamicNode(MixinTargetContext.java:709) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:480) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	... 36 more

**Comment by StewStrong** [comment]
```
Error loading class: kotlin/jvm/functions/Function0 (java.lang.ClassNotFoundException: kotlin.jvm.functions.Function0)
```
Install KotlinForForge
