### ISSUE TITLE
when assembled with eureka ship disappears and comes back when restarted

### ISSUE THREAD

**Issue by gigiyolo** [ValkyrienSkies/Valkyrien-Skies-2#469]
So i spent some time build an a airship on my 1.16.5 server and when i assembled it just disappeared and when i restarted it came back but i couldn't control it and in the server it says "[17:07:41] [Thread-16/ERROR] [or.va.co.ne.UdpServerImpl/]: Error in server network thread
java.lang.IllegalArgumentException: value already present: org.valkyrienskies.mod.common.util.MinecraftPlayer@842ef1d7
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:287) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:262) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at org.valkyrienskies.core.networking.UdpServerImpl.run(UdpServerImpl.kt:77) ~[valkyrienskies:?] {re:classloading}" every 5-10 seconds or so and i've tried removing performant which still didn't work and also tried removing other performance mods and also compatible mods which still didn't do anything

**Comment by Rubydesic** [comment]
Try disabling UDP in config
