### ISSUE TITLE
[1.18.2] Exception in server tick loop with vault hunters

### ISSUE THREAD

**Issue by thvless** [ValkyrienSkies/Valkyrien-Skies-2#501]
### Mod Name

Vault Hunters

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

              Discussed with Fluffy before, the solution is just to remove this randomizablecontainermixin from VS, it's not needed anymore

_Originally posted by @Rubydesic in https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/450#issuecomment-1522520091_
            
Originally the game would crash on startup with both mods present, based on that ^ comment i resorted to a rather hacky method removing the MixinRandomizableContainerBlockEntity from the mod jar, the game launches and valkyrien works normally
The game will however crash on entering a vault dimension with Exception in server tick loop (see crash and logs)

### Issue reproduction

- the_vault-1.18.2-3.8.0.2176 and latest (05/13/2023) VS nightly
- removed "feature.container_distance_check.MixinRandomizableContainerBlockEntity", from valkyrienskies-common.mixins.json
- removed MixinRandomizableContainerBlockEntity.class from \org\valkyrienskies\mod\mixin\feature\container_distance_check
- run minecraft
- enter vault portal

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11772158/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11772159/debug.log)
[crash-2023-06-16_17.05.30-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/11772161/crash-2023-06-16_17.05.30-server.txt)

**Comment by Th3M4ttman** [comment]
Can confirm, have tried everything and came to the same result. I've also had a read both our logs + the classes involved and it'd seem:

org.valkyrienskies.core.impl.util.assertions.stages.ConstraintFailedException: Constraints failed. Stages since last reset: [PRE_TICK, GET_LAST_TICK_CHANGES, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, POST_TICK_START, POST_TICK_GENERATED, POST_TICK_FINISH, GET_CURRENT_TICK_CHANGES, CLEAR_FOR_RESET, UPDATE_DIMENSIONS]

Is the issue. The stage enforcer raises the exception when there's too many UPDATE_CHUNKS in that array. So something is causing an error for the update chunks stage.

My guess is that it's something to do with the way The_Vault dynamically creates dimensions and Valkyrien Skies is struggling to understand it.

Any further info from any contributors would be great. I'm happy to contribute a code fix if I knew a lil more about the update_chunks stage

**Comment by SargeRyong** [comment]
Just wanted to confirm that I found the same thing in my world (I'd similarly stopped the VS2 mixin from loading by removing it from the mixins list) - this is the relevant part of my debug log.

`[08Nov2023 11:31:12.733] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos@7c7c258d, suppressing error
net.minecraft.ReportedException: Colliding entity with block
	at net.minecraft.world.entity.Entity.m_146872_(Entity.java:701) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.world.entity.Entity.m_6478_(Entity.java:668) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7185_(ServerGamePacketListenerImpl.java:839) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.m_5797_(ServerboundMovePlayerPacket.java:114) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.m_5797_(ServerboundMovePlayerPacket.java:42) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: org.valkyrienskies.core.impl.util.assertions.stages.ConstraintFailedException: Constraints failed. Stages since last reset: [PRE_TICK, GET_LAST_TICK_CHANGES, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, POST_TICK_START, POST_TICK_GENERATED, POST_TICK_FINISH, GET_CURRENT_TICK_CHANGES, CLEAR_FOR_RESET, UPDATE_DIMENSIONS]
Required stages matching predicate in the following order: [PRE_TICK, oneOf[UPDATE_DIMENSIONS, UPDATE_BLOCKS, UPDATE_CHUNKS], POST_TICK_START, POST_TICK_GENERATED, POST_TICK_FINISH, CLEAR_FOR_RESET, UPDATE_PLAYERS]
	at org.valkyrienskies.core.impl.util.assertions.stages.TickStageEnforcerImpl.stage(Unknown Source) ~[valkyrienskies-118-2.1.1-beta.2.jar%23265!/:?]
	at org.valkyrienskies.core.impl.game.ships.ShipObjectServerWorld.addDimension(Unknown Source) ~[valkyrienskies-118-2.1.1-beta.2.jar%23265!/:?]
	at net.minecraft.server.level.ServerLevel.handler$bfi000$onInit(ServerLevel.java:7772) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:228) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at iskallia.vault.core.world.storage.VirtualWorld.<init>(VirtualWorld.java:50) ~[the_vault-1.18.2-3.11.0.2625.jar%23254!/:1.18.2-3.11.0.2625]
	at iskallia.vault.core.world.storage.VirtualWorld.create(VirtualWorld.java:196) ~[the_vault-1.18.2-3.11.0.2625.jar%23254!/:1.18.2-3.11.0.2625]
	at iskallia.vault.world.data.ServerVaults.add(ServerVaults.java:75) ~[the_vault-1.18.2-3.11.0.2625.jar%23254!/:1.18.2-3.11.0.2625]
	at iskallia.vault.block.VaultPortalBlock.lambda$entityInside$5(VaultPortalBlock.java:114) ~[the_vault-1.18.2-3.11.0.2625.jar%23254!/:1.18.2-3.11.0.2625]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at iskallia.vault.block.VaultPortalBlock.m_7892_(VaultPortalBlock.java:108) ~[the_vault-1.18.2-3.11.0.2625.jar%23254!/:1.18.2-3.11.0.2625]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60682_(BlockBehaviour.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.world.entity.Entity.m_20101_(Entity.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.world.entity.Entity.m_146872_(Entity.java:696) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	... 18 more
[08Nov2023 11:31:12.743] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
org.valkyrienskies.core.impl.util.assertions.stages.ConstraintFailedException: Constraints failed. Stages since last reset: [PRE_TICK, GET_LAST_TICK_CHANGES, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, POST_TICK_START, POST_TICK_GENERATED, POST_TICK_FINISH, GET_CURRENT_TICK_CHANGES, CLEAR_FOR_RESET, UPDATE_DIMENSIONS, UPDATE_PLAYERS]
Required stages matching predicate in the following order: [PRE_TICK, oneOf[UPDATE_DIMENSIONS, UPDATE_BLOCKS, UPDATE_CHUNKS], POST_TICK_START, POST_TICK_GENERATED, POST_TICK_FINISH, CLEAR_FOR_RESET, UPDATE_PLAYERS]
	at org.valkyrienskies.core.impl.util.assertions.stages.TickStageEnforcerImpl.stage(Unknown Source) ~[valkyrienskies-118-2.1.1-beta.2.jar%23265!/:?]
	at org.valkyrienskies.core.impl.game.ships.ShipObjectServerWorld.setPlayers(Unknown Source) ~[valkyrienskies-118-2.1.1-beta.2.jar%23265!/:?]
	at net.minecraft.server.MinecraftServer.handler$bfa000$preTick(MinecraftServer.java:4561) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23290!/:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]`

**Comment by ewoudje** [comment]
There is a temporary fix jar in the discord, a proper fix will eventually:tm: be made
