### ISSUE TITLE
Server Not Loading : lateinit property CoreHooks has not been initialized

### ISSUE THREAD

**Issue by takemurak1005** [ValkyrienSkies/Valkyrien-Skies-2#513]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

When launched from the launcher, the problem does not occur. 
However, when launched on the server, the title error occurs.

### Issue reproduction

1. Install the following mods
  * eureka-1192-1.2.0-beta.1.jar  
  * valkyrienskies-1192-2.2.0-beta.2.jar 
  * kffmod-3.12.0.jar
2. startup forge server version 43.2.14

note : Although docker is used for the server, it is not necessary to prepare this environment. If you are unable to reproduce this, please let me know.
note2 : cloth-config-forge-8.2.88.jar is not include to mods folder.
note3 :[ There was a similar problem](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/253) with a closed Issue that appears to have recurred.
note4 : This issue was writed at DeepL ( Japanese→English/US ). Sorry if there is any strange english.

### Logs

Time: 2023-06-25 16:26:54
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.14-universal.jar%23110!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.2-43.2.14-universal.jar%23110!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23105!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.14.jar%2367!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at org.valkyrienskies.core.impl.hooks.CoreHooksImplKt.getCoreHooks(CoreHooksImpl.kt:40) ~[valkyrienskies-1192-2.2.0-beta.2.jar%23103!/:?] {re:classloading}
-- MOD vs_eureka --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.14.jar%23107!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.14.jar%23106!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

	Mod File: /data/mods/eureka-1192-1.2.0-beta.1.jar
	Failure message: VS Eureka Mod (vs_eureka) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.2.0-beta.1
	Mod Issue URL: https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues
	Exception message: kotlin.UninitializedPropertyAccessException: lateinit property CoreHooks has not been initialized
Stacktrace:
	at org.valkyrienskies.core.impl.hooks.CoreHooksImplKt.getCoreHooks(CoreHooksImpl.kt:40) ~[valkyrienskies-1192-2.2.0-beta.2.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.config.VSConfigClass.readOrCreateConfig(VSConfigClass.kt:49) ~[valkyrienskies-1192-2.2.0-beta.2.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.config.VSConfigClass$Companion.registerConfig(VSConfigClass.kt:250) ~[valkyrienskies-1192-2.2.0-beta.2.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.eureka.EurekaMod.init(EurekaMod.java:17) ~[eureka-1192-1.2.0-beta.1.jar%23101!/:?] {re:classloading}
	at org.valkyrienskies.eureka.forge.EurekaModForge.<init>(EurekaModForge.java:49) ~[eureka-1192-1.2.0-beta.1.jar%23101!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.14.jar%23107!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.14.jar%23106!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.4.72-microsoft-standard-WSL2
	Java Version: 17.0.7, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 7808384144 bytes (7446 MiB) / 8589934592 bytes (8192 MiB) up to 34359738368 bytes (32768 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5950X 16-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 48544.68
	Virtual memory used (MB): 46258.06
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 3157.67
	JVM Flags: 25 total; -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Xmx32G -Xms8G
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.14.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.14.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.14.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.14.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.14.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@3.12.0
		lowcodefml@null
	Mod List: 
		server-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: NOSIGNATURE
		kffmod-3.12.0.jar                                 |Kotlin For Forge              |kotlinforforge                |3.12.0              |COMMON_SET|Manifest: NOSIGNATURE
		valkyrienskies-1192-2.2.0-beta.2.jar              |Valkyrien Skies 2             |valkyrienskies                |2.2.0-beta.2        |COMMON_SET|Manifest: NOSIGNATURE
		eureka-1192-1.2.0-beta.1.jar                      |VS Eureka Mod                 |vs_eureka                     |1.2.0-beta.1        |ERROR     |Manifest: NOSIGNATURE
		cloth-config-forge-8.2.88.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.2.14-universal.jar                |Forge                         |forge                         |43.2.14             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
	Crash Report UUID: 3004778a-ba4c-481b-828e-c1a82c43d1cc
	FML: 43.2
	Forge: net.minecraftforge:43.2.14

**Comment by ejektaflex** [comment]
I also got this error on 1.20.1, using VS2 2.3.0-beta.3 and VS Eureka 1.3.0-beta.1.

**Comment by Osadar932** [comment]
+++

**Comment by takemurak1005** [comment]
I have solved this. By reducing the server CPU from 16 to 12, I was able to initialize in time and my minecraft worked.

However, this is an incomplete solution, I cannot play with 10 friends. Please improve it to use lateinit safely.

note:This comment was writed at DeepL ( Japanese→English/US ).Sorry if there is any strange english.
note2:I have good thoughts on this mod. Thanks for the daily development.

**Comment by burningtnt** [comment]
The loading of Forge mods are in a Thread Pool. When Valkyrienskies Core is loaded before Eureka Mod, nothing will occured. However, if Eureka Mod is loaded before Valkyrienskies Core, `CoreHooks` property hasn't been initialized. That's why decreasing the cores of CPU (will also decrease the thread count of Forge Mods Loading Thread Pool) can solve this problem.

**Comment by 8MiYile** [comment]
@ThePlasticPotato hey bro, look this
https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/513#issuecomment-2240939360

**Comment by RobertYyx** [comment]
Got this problem on 1.20.1 with valkyrienskies-120-2.3.0-beta.5 eureka-1201-1.5.1-beta.3 and clockwork-1.20.1-0.1.16-forge-b3b22e39fe.

**Comment by ejektaflex** [comment]
I honestly am not sure why `lateinit` (which you should avoid whenever you can) is used for mod loading when load order cannot be guaranteed. It might seem guaranteed, but clearly it's not.

**Comment by burningtnt** [comment]
> I honestly am not sure why `lateinit` (which you should avoid whenever you can) is used for mod loading when load order cannot be guaranteed. It might seem guaranteed, but clearly it's not.

A possible answer is the developer's PC doens't contain adequate CPU cores to re-produce this error. And another fact is this issue **HIGHTLY** rely on Forge mod loading order, which means even adding some other mods might be a possible workaround.

As these is 316 open issue for the developer to resolve, I guess it will take years until he/she/it(??? I'm not a native speaker) gives priority to this issue.

Good luck to all of you who encounter this issue and gather here.

**Comment by burningtnt** [comment]
OK. Good new for everyone who encounter this issue, I got a workground.

https://docs.minecraftforge.net/en/latest/gettingstarted/modfiles/#dependency-configurations

You need to open each of the plugins of vs-core, founds it's mods.toml, change `ordering="NONE"` to `ordering="AFTER"`.

**Comment by ejektaflex** [comment]
> A possible answer is the developer's PC doens't contain adequate CPU cores to re-produce this error. And another fact is this issue **HIGHTLY** rely on Forge mod loading order, which means even adding some other mods might be a possible workaround.

Oh, no, I just mean that Forge has loaded mods simultaneously (in threads) since 1.12. That's over 7 years ago - so I'd hope that the author knows that mods can load in any order, unless they specify a load order with `mods.toml`. Using something as unsafe as `lateinit` is crazy unless you can absolutely guarantee a load order.

It seems that they didn't even attempt to do that, though, if what you're saying is really true. 🙃 Ordering mods so that they load after their dependent library mod is essential.

**Comment by 1luik** [comment]
I'm extremely frustrated that this bug requires me to restart the server multiple times

**Comment by 1luik** [comment]
I'm extremely frustrated that this bug requires me to restart the server multiple times

**Comment by LogicWheat** [comment]
Still have this problem

**Comment by blockninja124** [comment]
@burningtnt Can you explain your workaround in more detail? I'm not quite sure what a "plugin of vs-core" is. If I can figure out the workaround, we could probably use it in a proper solution in VS itself.

**Comment by burningtnt** [comment]
> Can you explain your workaround in more detail? I'm not quite sure what a "plugin of vs-core" is. If I can figure out the workaround, we could probably use it in a proper solution in VS itself.

'Plugins of vs-core' theoretically means 'mods rely on Valkyrien Skies'.

As directly fixing this issue involves modifying the metadata of other mods, using some hacks in Valkyrien Skies would be OK as a workaround.

In the long run, I suggest providing a warning screen in developing environment if any mods that rely on Valkyrien Skies don't declare the 'ordering' key (See https://docs.minecraftforge.net/en/latest/gettingstarted/modfiles/#dependency-configurations ).

**Comment by blockninja124** [comment]
@burningtnt But I checked, and clockwork + tournament + VS addition + some others already specify to forge that they need to load AFTER. So I'm not sure that's actually the issue?

**Comment by burningtnt** [comment]
<img width="1750" height="945" alt="Image" src="https://github.com/user-attachments/assets/f4d89760-a82f-40fb-bd0c-c29c953cd8fe" />

Although I doesn't believe I'm actually 100% correct, please try making this field 'volatile', as FML doesn't guarantee that parent mods are loaded on the same thread. If this will cause performance issue, try getting this field in normal access mod and re-try in volatile mode if value is null.

It's really strange to have this issue, as non-volatile fields should flush to main memory somehow.

Sorry for my previous incorrect conclusion. Again, this issue dramatically relies on FML mod loading internal details,

**Comment by blockninja124** [comment]
Unfortunately that value is in VS core, so a dev higher up (Triode, Ruby, or Tomato) would have to fix it. I'll try discussing the issue with them to see if they agree with this fix.

**Comment by 8MiYile** [comment]
@blockninja124 Because the performance consumption of VS mod and extra mod is very high, and the issue is related to the loading order of FML, it should be fixed as soon as possible for the consideration of high-performance users, otherwise it will cause problems such as why high-performance computers can't run as well as ordinary performance computers

**Comment by blockninja124** [comment]
I haven't seen this issue occur since 2.4.0. Has anyone been able to reproduce it?
