### ISSUE TITLE
LinkageError with JourneyMap due to multiple copies of Log4J

### ISSUE THREAD

**Issue by Cynosphere** [ValkyrienSkies/Valkyrien-Skies-2#524]
### Mod Name

JourneyMap

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.19

### Mod Loader

Quilt

### Issue description

Identical to #257 but different classes targeted. 

Valkyrien Skies: `1201-2.3.0-beta.2`
JourneyMap: `1.20.1-5.9.10-fabric`

### Issue reproduction

Try to launch the game with both Valkyrien Skies and JourneyMap installed

### Logs

```
[18:35:17] [Render thread/ERROR]: Unhandled game exception
java.lang.LinkageError: loader constraint violation: when resolving method 'void org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(java.lang.String, org.apache.logging.log4j.Marker, java.lang.String, org.apache.logging.log4j.Level, org.apache.logging.log4j.message.Message, java.lang.Throwable)' the class loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @c038203 of the current class, journeymap/client/log/JMLogger, and the class loader 'app' for the method's defining class, org/apache/logging/log4j/core/impl/Log4jLogEvent, have different Class objects for the type org/apache/logging/log4j/Marker used in the signature (journeymap.client.log.JMLogger is in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @c038203, parent loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @29ee9faa; org.apache.logging.log4j.core.impl.Log4jLogEvent is in unnamed module of loader 'app')
	at journeymap.client.log.JMLogger.logProperties(JMLogger.java:149) ~[transformed-mod-journeymap.i0:0/:?]
	at journeymap.client.JourneymapClient.init(JourneymapClient.java:174) ~[transformed-mod-journeymap.i0:0/:?]
	at journeymap.client.JourneymapClient.lambda$onInitializeClient$0(JourneymapClient.java:115) ~[transformed-mod-journeymap.i0:0/:?]
	at org.quiltmc.qsl.lifecycle.api.client.event.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:43) ~[transformed-mod-quilt-lifecycle-events.i0:0/:?]
	at net.minecraft.class_310.handler$bho000$quilt_lifecycle_events$clientReady(class_310.java:12027) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.20.0-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.20.0-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.20.0-beta.1.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

**Comment by unilock** [comment]
Should be fixed with Quilt Loader 0.20.0-beta.11. (https://github.com/QuiltMC/quilt-loader/issues/342)
