### ISSUE TITLE
Physics do not work on the Server

### ISSUE THREAD

**Issue by Red1949** [ValkyrienSkies/Valkyrien-Skies-2#549]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

@triode_

Recently I hosted a server with PludOS. When I joined the game there was a red message:

"VS 2 physics are disabled on this server, because Krunch is not supported on this server! Current supported platforms are: ..." (Server is for MC Java so I do not know the reason)

Indeed, ships cannot move (Everyting works in singleplayer).
How to fix this?

### Issue reproduction

Host a server with PludOS,
Install Valkyrien Skies 2 and Eureka.
![Screenshot](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/assets/118655511/cecc9a76-98e8-4649-830a-b922bf2f366b)

**Comment by GameBurrow** [comment]
Having the same error. 1.19.2 Fabric version. Server is running with itzg/minecraft-server docker image on debian 11 machine.

**Comment by Red1949** [comment]
It means there's no way to solve this problem except change Server provider? Thank you for sharing that I'm not the only one who got mad from this.
Anyway, if mod's creator will find a resolve of this problem, I will leave this issue opened.

**Comment by GameBurrow** [comment]
Checking my own server logs, I found this:
```
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]: java.lang.RuntimeException: Couldn't load shared library 'libKrunchJni64.so' for target: Linux, 64-bit
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.physics_api_krunch.shared_library_loader.KrunchPhysicsAPISharedLibraryLoader.load(KrunchPhysicsAPISharedLibraryLoader.java:111)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.physics_api_krunch.KrunchBootstrap.loadNativeBinaries(KrunchBootstrap.kt:30)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.core.impl.program.VSCoreImpl.fromModule(VSCoreImpl.kt:89)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.core.impl.program.VSCoreImpl.newPipeline(VSCoreImpl.kt:69)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.core.impl.program.VSCoreServerImpl.newPipeline(VSCoreServerImpl.kt)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.mod.common.ShipSavedData$Companion.load(ShipSavedData.java:35)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.mod.common.ShipSavedData.load(ShipSavedData.java)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.class_26.method_120(class_26.java:71)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.class_26.method_20786(class_26.java:58)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.class_26.method_17924(class_26.java:42)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.server.MinecraftServer.handler$fac000$valkyrienskies$postCreateLevels(MinecraftServer.java:12891)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:361)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:324)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.class_3176.method_3823(class_3176.java:169)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at java.base/java.lang.Thread.run(Unknown Source)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: /tmp/libgdxminecraft/179e30c6/libKrunchJni64.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/libgdxminecraft/179e30c6/libKrunchJni64.so)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.physics_api_krunch.shared_library_loader.KrunchPhysicsAPISharedLibraryLoader.loadFile(KrunchPhysicsAPISharedLibraryLoader.java:307)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.physics_api_krunch.shared_library_loader.KrunchPhysicsAPISharedLibraryLoader.load(KrunchPhysicsAPISharedLibraryLoader.java:107)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  ... 16 more
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]: Caused by: java.lang.UnsatisfiedLinkError: /tmp/libgdxminecraft/179e30c6/libKrunchJni64.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/libgdxminecraft/179e30c6/libKrunchJni64.so)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at java.base/java.lang.Runtime.load0(Unknown Source)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at java.base/java.lang.System.load(Unknown Source)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.physics_api_krunch.shared_library_loader.KrunchPhysicsAPISharedLibraryLoader.loadFile(KrunchPhysicsAPISharedLibraryLoader.java:313)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.physics_api_krunch.shared_library_loader.KrunchPhysicsAPISharedLibraryLoader.loadFile(KrunchPhysicsAPISharedLibraryLoader.java:282)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  ... 17 more
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: We are not using UDP, falling back to TCP
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]: org.valkyrienskies.physics_api_krunch.KrunchBinariesNotLoadedException: Krunch libraries are not loaded!
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.physics_api_krunch.KrunchBootstrap.createKrunchPhysicsWorld(KrunchBootstrap.kt:14)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.core.impl.pipelines.VSPhysicsPipelineStage.<init>(VSPhysicsPipelineStage.kt:92)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.core.impl.pipelines.VSPhysicsPipelineStage_Factory.newInstance(VSPhysicsPipelineStage_Factory.java:27)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.core.impl.pipelines.VSPhysicsPipelineStage_Factory.get(VSPhysicsPipelineStage_Factory.java:19)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.core.impl.pipelines.VSPhysicsPipelineStage_Factory.get(VSPhysicsPipelineStage_Factory.java:9)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.core.impl.pipelines.VSPipelineImpl_Factory.get(VSPipelineImpl_Factory.java:44)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.core.impl.pipelines.VSPipelineImpl_Factory.get(VSPipelineImpl_Factory.java:12)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.core.impl.program.DaggerVSCoreServerFactory$VSPipelineComponentImpl.newPipeline(DaggerVSCoreServerFactory.java:222)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.core.impl.program.VSCoreImpl.fromModule(VSCoreImpl.kt:94)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.core.impl.program.VSCoreImpl.newPipeline(VSCoreImpl.kt:69)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.core.impl.program.VSCoreServerImpl.newPipeline(VSCoreServerImpl.kt)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.mod.common.ShipSavedData$Companion.load(ShipSavedData.java:35)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at org.valkyrienskies.mod.common.ShipSavedData.load(ShipSavedData.java)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.class_26.method_120(class_26.java:71)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.class_26.method_20786(class_26.java:58)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.class_26.method_17924(class_26.java:42)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.server.MinecraftServer.handler$fac000$valkyrienskies$postCreateLevels(MinecraftServer.java:12891)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:361)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:324)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.class_3176.method_3823(class_3176.java:169)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
2023-11-05 12:50:03 [10:50:03] [Server thread/INFO]: [STDERR]:  at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by SuperCraftAlex** [comment]
So basically its missing the ld library (ld-linux-x86-64.so.2)
you need to make sure that this library exists on your server.
im 99% surr that it already exists but not under this name

**Comment by GameBurrow** [comment]
> So basically its missing the ld library (ld-linux-x86-64.so.2) you need to make sure that this library exists on your server. im 99% surr that it already exists but not under this name

Seems to be an issue with using alpine linux, it doesn't have that by default (https://stackoverflow.com/questions/66963068/docker-alpine-executable-binary-not-found-even-if-in-path)  - at first glance seemed to fix it by changing the docker image to ubuntu based, can't fully test it until VS2 supports the latest Sodium as rest of my modpack has been updated to that.

**Comment by thetheaplant** [comment]
User error, make sure ld and GlibC are installed.
