### ISSUE TITLE
Incompatibility with Lightman's discord integration

### ISSUE THREAD

**Issue by Waterspark63** [ValkyrienSkies/Valkyrien-Skies-2#570]
### Mod Name

Lightman's Discord Integration

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

When you have both ValkyrienSkies, and Lightman's Discord installed, because both of them are providing 'com.fasterxml.jackson.core', which causes the following crash (The 'issue' mod changes with every single load, but looking at the mod files, I figured out it was VS that was incompatible):

Forge: 40.2.10
Lightman's discord version: 1.18-2.0.0, Lightman's Currency: 1.18.2-2.1.2.2, LCTech: 1.18.2-0.2.0.0, VS: 1.18-2.1.0-Beta-14
```
Exception in thread "main" java.lang.module.ResolutionException: Modules lightmansdiscord and com.fasterxml.jackson.core export package com.fasterxml.jackson.core to module minecraft
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
```

Is there any possibility of getting these two to play together nicely? I also put this issue at the Lightman's Discord github [here](https://github.com/Lightman314/Lightmans-Discord-Integration/issues/19)

### Issue reproduction

Just launch the game with the mods installed.

### Logs

It doesn't show in the log, only on the console window (server)

**Comment by Rubydesic** [comment]
This is an issue with the other mod. VS is using the correct way (jij) to include the library, while this mod is shading it. Suggest you delete the com/fasterxml/jackson/core file from the other mod as an interim solution
