### ISSUE TITLE
Sodium and VS2

### ISSUE THREAD

**Issue by ballhammer** [ValkyrienSkies/Valkyrien-Skies-2#590]
### Mod Name

Sodium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

Game instant crash when attempting to load the game when Sodium and VS2 are installed.

### Issue reproduction

1. have sodium and VS2 installed.
2. Game crashes on startup.

### Logs

[crash-2023-09-28_10.33.16-client.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/12750880/crash-2023-09-28_10.33.16-client.txt)

**Comment by PriestOfFerns** [comment]
Known issue, 0.5.X versions of sodium are known to be incompatible be VS2. Older versions still work though

**Comment by MaverickMartyn** [comment]
This leaves me a little stuck.
I tried downgrading Rubidium to 0.6.5, but I also use Create (and intend on trying out the Clockwork addon which integrates with it), but Create automatically includes Flywheel, which depends on Rubidium 0.7.0.
This leaves me with no option but to leave out Valkyrien Skies for the time being, which effectively puts a stop to my pack for now, since this mod was intended to be an integral part of it. :/
Hoping for a fix soon. :)

**Comment by PriestOfFerns** [comment]
@MaverickMartyn 

Not sure about rubidium, but I ran a 0.4.1 Sodium clockwork modpack without that many issues (Other than 1 crash due to some weird shader bug).

In any case, a fix probably isn't going to come out soon, since Ruby wants to finish addon API before fixing compat with >0.5 versions of sodium

**Comment by sighlessm** [comment]
Crashlog from ATlauncher

`[22/10/2023 16:21:29 PM] ---- Minecraft Crash Report ----
[22/10/2023 16:21:29 PM] // You should try our sister game, Minceraft!
[22/10/2023 16:21:29 PM] 
[22/10/2023 16:21:29 PM] Time: 2023-10-22 16:21:29
[22/10/2023 16:21:29 PM] Description: Initializing game
[22/10/2023 16:21:29 PM] 
[22/10/2023 16:21:29 PM] java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer failed
[22/10/2023 16:21:29 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
[22/10/2023 16:21:29 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
[22/10/2023 16:21:29 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
[22/10/2023 16:21:29 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
[22/10/2023 16:21:29 PM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[22/10/2023 16:21:29 PM] 	at net.minecraft.class_761.handler$dom000$sodium$init(class_761.java:13968)
[22/10/2023 16:21:29 PM] 	at net.minecraft.class_761.<init>(class_761.java:307)
[22/10/2023 16:21:29 PM] 	at net.minecraft.class_310.<init>(class_310.java:583)
[22/10/2023 16:21:29 PM] 	at net.minecraft.client.main.Main.main(Main.java:211)
[22/10/2023 16:21:29 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
[22/10/2023 16:21:29 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[22/10/2023 16:21:29 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[22/10/2023 16:21:29 PM] Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
[22/10/2023 16:21:29 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
[22/10/2023 16:21:29 PM] 	... 11 more
[22/10/2023 16:21:29 PM] Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer from mod valkyrienskies] from phase [DEFAULT] in config [valkyrienskies-common.mixins.json] FAILED during APPLY
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
[22/10/2023 16:21:29 PM] 	... 14 more
[22/10/2023 16:21:29 PM] Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Redirect annotation on renderShipChunkBlockEntity could not find any targets matching 'Lme/jellysquid/mods/sodium/client/render/SodiumWorldRenderer;renderTileEntities(Lnet/minecraft/class_4587;Lnet/minecraft/class_4599;Lit/unimi/dsi/fastutil/longs/Long2ObjectMap;Lnet/minecraft/class_4184;F)V' in me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer. Using refmap valkyrienskies-1201-common-refmap.json [PREINJECT Applicator Phase -> valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer from mod valkyrienskies -> Prepare Injections ->  -> redirect$ehc000$valkyrienskies$renderShipChunkBlockEntity(Lnet/minecraft/class_824;Lnet/minecraft/class_2586;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;Lnet/minecraft/class_4587;Lnet/minecraft/class_4599;Lit/unimi/dsi/fastutil/longs/Long2ObjectMap;Lnet/minecraft/class_4184;F)V -> Parse]
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.injection.struct.RedirectInjectionInfo.<init>(RedirectInjectionInfo.java:44)
[22/10/2023 16:21:29 PM] 	at jdk.internal.reflect.GeneratedConstructorAccessor67.newInstance(Unknown Source)
[22/10/2023 16:21:29 PM] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22/10/2023 16:21:29 PM] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[22/10/2023 16:21:29 PM] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
[22/10/2023 16:21:29 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[22/10/2023 16:21:29 PM] 	... 14 more
[22/10/2023 16:21:29 PM] 
[22/10/2023 16:21:29 PM] 
[22/10/2023 16:21:29 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[22/10/2023 16:21:29 PM] ---------------------------------------------------------------------------------------
[22/10/2023 16:21:29 PM] 
[22/10/2023 16:21:29 PM] -- Head --
[22/10/2023 16:21:29 PM] Thread: Render thread
[22/10/2023 16:21:29 PM] Stacktrace:
[22/10/2023 16:21:29 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
[22/10/2023 16:21:29 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
[22/10/2023 16:21:29 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
[22/10/2023 16:21:29 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
[22/10/2023 16:21:29 PM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[22/10/2023 16:21:29 PM] 	at net.minecraft.class_761.handler$dom000$sodium$init(class_761.java:13968)
[22/10/2023 16:21:29 PM] 	at net.minecraft.class_761.<init>(class_761.java:307)
[22/10/2023 16:21:29 PM] 	at net.minecraft.class_310.<init>(class_310.java:583)
[22/10/2023 16:21:29 PM] 
[22/10/2023 16:21:29 PM] -- Initialization --
[22/10/2023 16:21:29 PM] Details:
[22/10/2023 16:21:29 PM] 	Modules: 
[22/10/2023 16:21:29 PM] 		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		CRYPT32.dll:Crypto API32:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.2361 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.22621.2215:Microsoft Corporation
[22/10/2023 16:21:29 PM] 		DBGHELP.DLL:Windows Image Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		DEVOBJ.dll:Device Information Set DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		DNSAPI.dll:DNS Client API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		Easyhk64.dll:EasyHook Native DLL (64-bit) (beta):2.8.0.0:easyhook.codeplex.com
[22/10/2023 16:21:29 PM] 		GDI32.dll:GDI Client DLL:10.0.22621.2215 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		GLU32.dll:OpenGL Utility Library DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		MMDevApi.dll:MMDevice API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		MSCTF.dll:MSCTF Server DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		MacType64.Core.dll:The Ultimate Font Rasterizer:1.2023.531.1:2ch & THEMEX & everyone
[22/10/2023 16:21:29 PM] 		MacType64.dll:MacType ????:1.2021.621.2:MacType
[22/10/2023 16:21:29 PM] 		MpOav.dll:IOfficeAntiVirus Module:4.18.23090.2008 (b0d7cf273f4b179b8031bda447c0e07aca8eb8b4):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.1992 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		Ole32.dll:Microsoft OLE for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		Oleacc.dll:Active Accessibility Core Component:7.2.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		OpenAL.dll:Main implementation library:1.21.1:
[22/10/2023 16:21:29 PM] 		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		SETUPAPI.dll:Windows Setup API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		SHCORE.dll:SHCORE:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		SHELL32.dll:Windows Shell Common Dll:10.0.22621.2361 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		USERENV.dll:Userenv:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
[22/10/2023 16:21:29 PM] 		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		WINHTTP.dll:Windows HTTP Services:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		WINMM.dll:MCI API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		WINSTA.dll:Winstation Library:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.22621.2361 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		apphelp.dll:Application Compatibility Client Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		awt.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
[22/10/2023 16:21:29 PM] 		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.2361 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		cfgmgr32.dll:Configuration Manager DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		combase.dll:Microsoft COM for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		cryptnet.dll:Crypto Network Related API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		d2d1.dll:Microsoft D2D Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		dhcpcsvc.DLL:DHCP Client Service:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] 		dhcpcsvc6.DLL:DHCPv6 Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
[22/10/2023 16:21:29 PM] #@!@# Game crashed! Crash report saved to: #@!@# **USERSDIR**\instances\Minecraft1201withFabric\crash-reports\crash-2023-10-22_16.21.29-client.txt
[22/10/2023 16:21:30 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[22/10/2023 16:21:30 PM] Checking for updated files!
[22/10/2023 16:21:34 PM] Copied Log to clipboard`

**Comment by gardenappl** [comment]
> This leaves me a little stuck. I tried downgrading Rubidium to 0.6.5, but I also use Create (and intend on trying out the Clockwork addon which integrates with it), but Create automatically includes Flywheel, which depends on Rubidium 0.7.0. This leaves me with no option but to leave out Valkyrien Skies for the time being, which effectively puts a stop to my pack for now, since this mod was intended to be an integral part of it. :/ Hoping for a fix soon. :)

Create 1.20.1-0.5.1.d is compatible with older Rubidium. But it's still annoying since you have to also downgrade many Create addons to work with it, and potentially introduce other bugs by mixing and matching old and new versions of mods.

**Comment by JoelZBub** [comment]
duplicate of #569 and #580

**Comment by ewoudje** [comment]
Closing in favor of https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/556
