### ISSUE TITLE
Sodium and Valkyrian Skies crash<title>

### ISSUE THREAD

**Issue by Eagletanker** [ValkyrienSkies/Valkyrien-Skies-2#644]
### Mod Name

Sodium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

Upon loading Valk and Sodium together, the game instantly crashes when it opens. I expect it not to do that, considering how widely sodium is used in modpacks and such. 

### Issue reproduction

Load Sodium and Valkyrian Skies together.

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13588684/latest.log)

(Don't have Debug.log, sorry)

From crash log
ava.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_761.handler$zkm000$sodium$init(class_761.java:4468)
	at net.minecraft.class_761.<init>(class_761.java:307)
	at net.minecraft.class_310.<init>(class_310.java:583)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector renderShipChunkBlockEntity(Lnet/minecraft/class_824;Lnet/minecraft/class_2586;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;Lnet/minecraft/class_4587;Lnet/minecraft/class_4599;Lit/unimi/dsi/fastutil/longs/Long2ObjectMap;Lnet/minecraft/class_4184;F)V in valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer from mod valkyrienskies failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap valkyrienskies-1201-common-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more

**Comment by Eagletanker** [comment]
Whoops its a duplicate, I see it's a known issue. Sad that we can't play with newer versions of sodium but oh well, hopefully you guys can figure out how to make the two play nice again.
