### ISSUE TITLE
"this.shipWorld" is null

### ISSUE THREAD

**Issue by Chrithon** [ValkyrienSkies/Valkyrien-Skies-2#666]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

# Information
* OS: Ubuntu 23.04 (GNU/Linux 6.1.31 riscv64)
* JDK: OpenJDK 64-Bit Server VM Fizzed19.36 (build 19.0.1+10, mixed mode)->OpenJDK 64-Bit Server VM (build 17.0.9+9-Ubuntu-123.04, mixed mode, sharing)->OpenJDK 64-Bit Server VM Temurin-21.0.1+12-202312232351 (build 21.0.1-beta+12-202312232351, mixed mode, sharing)
* Mod Version: v2.1.1-beta.4
* Server: mohist-1.18.2-127->mohist-1.18.2-135->arclight-1.18.2-1.0.10-033f7507
# Description
My server can't run and shows:
```
"org.valkyrienskies.core.apigame.world.ServerShipWorldCore.setGameServer(org.valkyrienskies.core.apigame.GameServer)" because "this.shipWorld" is null
```

### Issue reproduction

- [x] Changed JDK: OpenJDK 64-Bit Server VM Fizzed19.36 (build 19.0.1+10, mixed mode)->OpenJDK 64-Bit Server VM (build 17.0.9+9-Ubuntu-123.04, mixed mode, sharing)->OpenJDK 64-Bit Server VM Temurin-21.0.1+12-202312232351 (build 21.0.1-beta+12-202312232351, mixed mode, sharing) (not work)
- [x] Changed Server:  mohist-1.18.2-127->mohist-1.18.2-135->arclight-1.18.2-1.0.10-033f7507 (not work)
- [x] Searched the web (still not solved) 

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13793575/latest.log)
[debug.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13793576/debug.log)

**Comment by creeloper27** [comment]
I am having the same exact problem though on a Fabric server.

`server console error`
```
[16:49:14] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "org.valkyrienskies.core.apigame.world.ServerShipWorldCore.setGameServer(org.valkyrienskies.core.apigame.GameServer)" because "this.shipWorld" is null
        at net.minecraft.server.MinecraftServer.handler$eol000$valkyrienskies$preStopServer(MinecraftServer.java:10655) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:537) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:703) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

`crash log`
[crash-2024-03-27_16.49.14-server.txt](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/14775931/crash-2024-03-27_16.49.14-server.txt)

**Comment by Gulpie** [comment]
same here but nothing fixes it

**Comment by Kitieshka** [comment]
same problem on fabric 1.20.1

**Comment by thetheaplant** [comment]
If you have the same problem and the fix listed does not fix it, make a new issue.

**Comment by PassKnoedel** [comment]
I had the same issue and managed to resolve it by changing the server port to something like 25566 since i had another server running on the default 25565 port

**Comment by jevans10** [comment]
I'm also having this issue. I'm using a 2009 iMac to fun my fabric server. I've tried removing sodium, creative interactive, and changing the port.

**Comment by MonkaKokosowa** [comment]
Although not an ideal solution, if someone is just looking for reviving the world file without deleting any mods you can delete the `vs_ship_data.dat` file in the `data` directory inside the save file.

**Comment by PriestOfFerns** [comment]
arc light, mohist and other plugin-mod hybrid servers are usually incompatible with VS2

**Comment by LuChiChick** [comment]
Switching to the "Microsoft Build of OpenJDK" resolved the problem.

I encountered this problem when trying to run the server on an old android phone using Termux. The server works fine on my PC, but when I copied it to the Termux environment, I got the error `"this.shipWorld" is null` and server gets crash. This issue occurred when I tried changing the server core as well. Both _Mohist_ and _Arclight_ runs fine on my PC, but they crash in the Termux environment. The only thing I could think of was a difference in the JDK versions they were using. After installing a working Ubuntu image for Termux via proot-distro, I followed the official [Microsoft Guide](https://learn.microsoft.com/en-us/java/openjdk/install#install-on-ubuntu) to install the corresponding JDK sames as my PC run (it installed by winget), and eventually, it ran successfully.

Maybe the "Microsoft Build of OpenJDK" has a built-in handling process for errors like `java.lang.NullPointerException`?

server core: Mohist/Arclight
game version: 1.20.1
JDK info: 
```bash
$java -version
openjdk version "17.0.13" 2024-10-15 LTS
OpenJDK Runtime Environment Microsoft-10376486 (build 17.0.13+11-LTS)
OpenJDK 64-Bit Server VM Microsoft-10376486 (build 17.0.13+11-LTS, mixed mode, sharing)
```

**Comment by creeloper27** [comment]
> Switching to the "Microsoft Build of OpenJDK" resolved the problem.
> 
> I encountered this problem when trying to run the server on an old android phone using Termux. The server works fine on my PC, but when I copied it to the Termux environment, I got the error `"this.shipWorld" is null` and server gets crash. This issue occurred when I tried changing the server core as well. Both _Mohist_ and _Arclight_ runs fine on my PC, but they crash in the Termux environment. The only thing I could think of was a difference in the JDK versions they were using. After installing a working Ubuntu image for Termux via proot-distro, I followed the official [Microsoft Guide](https://learn.microsoft.com/en-us/java/openjdk/install#install-on-ubuntu) to install the corresponding JDK sames as my PC run (it installed by winget), and eventually, it ran successfully.
> 
> Maybe the "Microsoft Build of OpenJDK" has a built-in handling process for errors like `java.lang.NullPointerException`?
> 
> server core: Mohist/Arclight
> game version: 1.20.1
> JDK info: 
> ```bash
> $java -version
> openjdk version "17.0.13" 2024-10-15 LTS
> OpenJDK Runtime Environment Microsoft-10376486 (build 17.0.13+11-LTS)
> OpenJDK 64-Bit Server VM Microsoft-10376486 (build 17.0.13+11-LTS, mixed mode, sharing)
> ```

That's very useful to know! Thanks for sharing, at least we can use this trick until it's properly fixed to work on other JVMs as well, just to be clear, with "it ran successfully" you mean that everything inside the minecraft server and the various mod functionalities and features also work fine?

**Comment by LuChiChick** [comment]
> 
> That's very useful to know! Thanks for sharing, at least we can use this trick until it's properly fixed to work on other JVMs as well, just to be clear, with "it ran successfully" you mean that everything inside the minecraft server and the various mod functionalities and features also work fine?

My server loaded a total of 29 mods, including `BiomesOPlenty`, `Create`, `Ice and Fire`, `TConstruct`,`Quark` and some prerequisite mods. Among them, the mods related to Valkyrien Skies are `Eureka! Ships! for Valkyrien Skies` and `VS Addition`.

When the server generates the initial terrain or new chunks, the following error may appear in the console:
```log
[13:45:18 WARN] [o.v.c.i.s.Ak]: Too many physics frames in the physics frame queue. Is the game stage broken?
[13:45:18 INFO]: Preparing spawn area: 55%
[13:45:19 INFO]: Preparing spawn area: 63%
[13:45:19 WARN] [o.v.c.i.s.Ak]: Too many physics frames in the physics frame queue. Is the game stage broken?
[13:45:19 INFO]: Preparing spawn area: 71%
[13:45:20 INFO]: Preparing spawn area: 80%
[13:45:20 WARN] [o.v.c.i.s.Ak]: Too many physics frames in the physics frame queue. Is the game stage broken?
[13:45:20 INFO]: Preparing spawn area: 80%
[13:45:21 INFO]: Preparing spawn area: 80%
[13:45:21 WARN] [o.v.c.i.s.Ak]: Too many physics frames in the physics frame queue. Is the game stage broken?
[13:45:21 INFO]: Preparing spawn area: 93%
[13:45:22 INFO]: Time elapsed: 48973 ms
[13:45:22 INFO]: Done (89.007s)! For help, type "help"
[13:45:22 INFO]: Successfully initialized permission handler forge:default_handler
```
This seems to be a known issue among the developers, and it is confirmed to be addressed in a future version.(check here #323 )

Moving to chunks that haven't generated or loaded  yet may cause severe server lag or even crashes.A good solution is to use a chunk pre-generation plugin like `Chunky` to pre-generate a large number of chunks to ensuring a smooth gameplay experience. This method is also effective for servers running mods like `The Twilight Forest`, which have a significant impact on the server during chunk generation.

In addition to this, when structures with physical properties built using items from `Eureka` are moved, the server console will pop out a large number of error messages:
```log
[23:05:09 ERROR] [VS2 Get Entities Mixin]: java.lang.Exception: Collision box is too big! AABB[-2.8661747650000006E7, 63.26608642811232, -210.81369059346616] -> [-65.29386541619897, 65.0660863804286, 1.2290063650000006E7] returning empty list! this might break things
[23:05:14 ERROR] [VS2 Get Entities Mixin]: java.lang.Exception: Collision box is too big! AABB[-2.8661747650000006E7, 63.28539819784468, -212.3247118876897] -> [-72.72516114112337, 65.08539815016096, 1.2290063650000006E7] returning empty list! this might break things
[23:05:19 ERROR] [VS2 Get Entities Mixin]: java.lang.Exception: Collision box is too big! AABB[-2.8661747650000006E7, 63.280561709072465, -217.19084509847625] -> [-79.0198454288498, 65.08056166138874, 1.2290063650000006E7] returning empty list! this might break things
[23:05:24 ERROR] [VS2 Get Entities Mixin]: java.lang.Exception: Collision box is too big! AABB[-2.8661747650000006E7, 63.30091734654227, -221.16310495902206] -> [-91.77502816160597, 65.10091729885855, 1.2290063650000006E7] returning empty list! this might break things
[23:05:29 ERROR] [VS2 Get Entities Mixin]: java.lang.Exception: Collision box is too big! AABB[-2.8661747650000006E7, 63.30409855927616, -230.4499630257902] -> [-102.41467041921372, 65.10409851159244, 1.2290063650000006E7] returning empty list! this might break things
```

However, when I checked the server's current TPS status using the `/tps` command, I found that the TPS didn't drop too much, and there was no noticeable lag in the game,maybe it's because my ship is too simple and cute? :P

`screenshoot`
![Image](https://github.com/user-attachments/assets/11941cd1-921e-4f31-8adb-46df65ae6bcd)

**Comment by blockninja124** [comment]
Shipworld is null I believe is still a bug, however from what I've seen it happens as a knock-on affect from another crash further up. For example, another mod crashes (but not fully fatally), and that causes the ship world to be null and VS to look like the culprit. These are just my suspicions though
