### ISSUE TITLE
[Game crash] Valkyrien Skies acts like water to Sodium mod

### ISSUE THREAD

**Issue by MCAlexisYT** [ValkyrienSkies/Valkyrien-Skies-2#674]
### Mod Name

Sodium, and maybe Iris

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

The title is based off of a real-life interaction between water and the "element" called "sodium". In this case, the explosion/chemical reaction that would happen if a block of sodium were thrown into water is the game crashing with a mixin injection error, which would normally happen if you were to load (for example) a Fabric 1.14.4 mod into 1.20.1. 
And yes, I've tried with Indium, but I got the same result: a game crash with a mixin injection error.

### Issue reproduction

Download the following mods: 

- Valkyrien Skies
- Eureka!
- Sodium
- Iris Shaders
- Fabric API

And start the game. Simple as that.
It also occurs even with Indium.

### Logs

[16:47:38] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.3
[16:47:39] [main/INFO]: Loading 77 mods:
	- fabric-api 0.91.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.12+215bbe9677
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.10+57aed33f77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.3.3+d7b148e077
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.39+ae9f657a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.11+d7b148e077
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.2.0+96dfa95977
	   |-- fabric-loot-tables-v1 1.1.44+9e7660c677
	   |-- fabric-message-api-v1 5.1.8+d7b148e077
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.2+4ee0bc6077
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.2.0+39a511ba77
	   |-- fabric-renderer-indigo 1.5.0+39a511ba77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.7+29de845d77
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.3+c81d263177
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabricloader 0.15.3
	   \-- mixinextras 0.3.2
	- iris 1.6.11
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- minecraft 1.20.1
	- sodium 0.5.3
	- valkyrienskies 2.3.0-beta.4
	   |-- cloth-config 11.0.99
	   |    \-- cloth-basic-math 0.6.1
	   \-- fabric-language-kotlin 1.8.5+kotlin.1.7.20
	        |-- org_jetbrains_kotlin_kotlin-reflect 1.7.20
	        |-- org_jetbrains_kotlin_kotlin-stdlib 1.7.20
	        |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.20
	        |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.20
	        |-- org_jetbrains_kotlinx_atomicfu-jvm 0.18.4
	        |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	        |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	        |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	        |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1
	        |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1
	        \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1
	- vs_eureka 1.3.0-beta.2
[16:47:46] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Utilisateur/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[16:47:46] [main/INFO]: Compatibility level set to JAVA_16
[16:47:46] [main/INFO]: Compatibility level set to JAVA_17
[16:47:47] [main/INFO]: Loaded configuration file for Sodium: 41 options available, 3 override(s) found
[16:47:47] [main/WARN]: Reference map 'eureka-1201-fabric-refmap.json' for vs_eureka.mixins.json could not be read. If this is a development environment you can ignore this message
[16:47:48] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[16:47:48] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[16:47:48] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[16:47:48] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[16:47:48] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[16:47:48] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[16:47:48] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[16:47:48] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[16:47:48] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/ChunkTracker (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/ChunkTracker)
[16:47:48] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.render.chunk.ChunkTracker was not found valkyrienskies-common.mixins.json:mod_compat.sodium.MixinChunkTracker from mod valkyrienskies
[16:47:48] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/RegionChunkRenderer (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/RegionChunkRenderer)
[16:47:48] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer was not found valkyrienskies-common.mixins.json:mod_compat.sodium.MixinRegionChunkRenderer from mod valkyrienskies
[16:47:48] [main/WARN]: Error loading class: com/jozufozu/flywheel/backend/instancing/instancing/InstancingEngine (java.lang.ClassNotFoundException: com/jozufozu/flywheel/backend/instancing/instancing/InstancingEngine)
[16:47:48] [main/WARN]: Error loading class: com/jozufozu/flywheel/backend/instancing/blockentity/BlockEntityInstanceManager (java.lang.ClassNotFoundException: com/jozufozu/flywheel/backend/instancing/blockentity/BlockEntityInstanceManager)
[16:47:48] [main/WARN]: Error loading class: com/jozufozu/flywheel/backend/instancing/InstanceManager (java.lang.ClassNotFoundException: com/jozufozu/flywheel/backend/instancing/InstanceManager)
[16:47:48] [main/WARN]: Error loading class: com/jozufozu/flywheel/backend/instancing/InstanceWorld (java.lang.ClassNotFoundException: com/jozufozu/flywheel/backend/instancing/InstanceWorld)
[16:47:48] [main/WARN]: Error loading class: com/jozufozu/flywheel/backend/instancing/instancing/InstancingEngine (java.lang.ClassNotFoundException: com/jozufozu/flywheel/backend/instancing/instancing/InstancingEngine)
[16:47:48] [main/WARN]: Error loading class: com/sonicether/soundphysics/SoundPhysics (java.lang.ClassNotFoundException: com/sonicether/soundphysics/SoundPhysics)
[16:47:49] [main/INFO]: Searching for graphics cards...
[16:47:50] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=INTEL, name=Intel(R) HD Graphics Family, version=DriverVersion=20.19.15.5126]
[16:47:51] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[16:48:05] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 657 milliseconds
[16:48:11] [Render thread/INFO]: [STDERR]: Version: 3.3.1 SNAPSHOT
[16:48:11] [Render thread/INFO]: [STDERR]: 	 OS: Windows 10 v10.0
[16:48:11] [Render thread/INFO]: [STDERR]: 	JRE: Windows amd64 17.0.9
[16:48:11] [Render thread/INFO]: [STDERR]: 	JVM: OpenJDK 64-Bit Server VM v17.0.9+8-LTS by Azul Systems, Inc.
[16:48:11] [Render thread/INFO]: [STDERR]: Loading JNI library: lwjgl
[16:48:11] [Render thread/INFO]: [STDERR]: 	Module: org.lwjgl
[16:48:11] [Render thread/INFO]: [STDERR]: 	Loaded from org.lwjgl.librarypath: C:\Users\Utilisateur\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.1-0.15.3\lwjgl.dll
[16:48:11] [Render thread/INFO]: [STDERR]: Loading library: jemalloc
[16:48:11] [Render thread/INFO]: [STDERR]: 	Module: org.lwjgl.jemalloc
[16:48:11] [Render thread/INFO]: [STDERR]: 	Loaded from org.lwjgl.librarypath: C:\Users\Utilisateur\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.1-0.15.3\jemalloc.dll
[16:48:11] [Render thread/INFO]: [STDERR]: MemoryUtil allocator: JEmallocAllocator
[16:48:11] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:48:12] [Render thread/INFO]: Setting user: _[Minecraft username]_
[16:48:13] [Render thread/ERROR]: No data fixer registered for valkyrienskies:ship_mounting_entity
[16:48:16] [Render thread/INFO]: [STDOUT]: registering network handlers
[16:48:19] [Render thread/ERROR]: No data fixer registered for ship_helm
[16:48:19] [Render thread/ERROR]: No data fixer registered for engine
[16:48:19] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[16:48:20] [Render thread/INFO]: [STDERR]: Loading library: glfw
[16:48:20] [Render thread/INFO]: [STDERR]: 	Module: org.lwjgl.glfw
[16:48:20] [Render thread/INFO]: [STDERR]: 	Loaded from org.lwjgl.librarypath: C:\Users\Utilisateur\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.1-0.15.3\glfw.dll
[16:48:20] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[16:48:20] [Render thread/INFO]: [STDERR]: Java 9 check intrinsics enabled
[16:48:20] [Render thread/INFO]: [STDERR]: Closure Registry: simple
[16:48:21] [Render thread/INFO]: [STDERR]: Loading JNI library: lwjgl_opengl
[16:48:21] [Render thread/INFO]: [STDERR]: 	Module: org.lwjgl.opengl
[16:48:21] [Render thread/INFO]: [STDERR]: 	Loaded from org.lwjgl.librarypath: C:\Users\Utilisateur\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.1-0.15.3\lwjgl_opengl.dll
[16:48:21] [Render thread/INFO]: [STDERR]: Loading library: opengl32
[16:48:21] [Render thread/INFO]: [STDERR]: 	Module: org.lwjgl.opengl
[16:48:21] [Render thread/INFO]: [STDERR]: 	opengl32.dll not found in org.lwjgl.librarypath=C:\Users\Utilisateur\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.1-0.15.3
[16:48:21] [Render thread/INFO]: [STDERR]: 	Loaded from system paths: C:\WINDOWS\SYSTEM32\opengl32.dll
[16:48:21] [Render thread/INFO]: [STDERR]: Java 10 multiplyHigh enabled
[16:48:21] [Render thread/INFO]: [STDERR]: Java 9 text decoding enabled
[16:48:21] [Render thread/INFO]: OpenGL Vendor: Intel
[16:48:21] [Render thread/INFO]: OpenGL Renderer: Intel(R) HD Graphics 4400
[16:48:21] [Render thread/INFO]: OpenGL Version: 3.2.0 - Build 20.19.15.5126
[16:48:21] [Render thread/INFO]: [STDERR]: Loading JNI library: lwjgl_stb
[16:48:21] [Render thread/INFO]: [STDERR]: 	Module: org.lwjgl.stb
[16:48:21] [Render thread/INFO]: [STDERR]: 	Loaded from org.lwjgl.librarypath: C:\Users\Utilisateur\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.1-0.15.3\lwjgl_stb.dll
[16:48:21] [Render thread/INFO]: Debug functionality is disabled.
[16:48:21] [Render thread/INFO]: DSA support not detected.
[16:48:21] [Render thread/INFO]: Shaders are disabled because no valid shaderpack is selected
[16:48:21] [Render thread/INFO]: Shaders are disabled
[16:48:22] [Render thread/INFO]: [STDERR]: Loading library: OpenAL
[16:48:22] [Render thread/INFO]: [STDERR]: 	Module: org.lwjgl.openal
[16:48:22] [Render thread/INFO]: [STDERR]: 	Loaded from org.lwjgl.librarypath: C:\Users\Utilisateur\AppData\Roaming\com.modrinth.theseus\meta\natives\1.20.1-0.15.3\OpenAL.dll
[16:48:24] [Render thread/INFO]: Hardware information:
[16:48:24] [Render thread/INFO]: CPU: 4x Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
[16:48:24] [Render thread/INFO]: GPU: Intel(R) HD Graphics 4400 (Supports OpenGL 3.2.0 - Build 20.19.15.5126)
[16:48:24] [Render thread/INFO]: OS: Windows 10 (10.0)
[16:48:25] [Render thread/INFO]: Instancing error handler class org.valkyrienskies.mod.mixin.ValkyrienMixinErrorHandler
[16:48:25] [Render thread/ERROR]: Mixin apply for mod valkyrienskies failed valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer from mod valkyrienskies -> me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Redirect annotation on renderShipChunkBlockEntity could not find any targets matching 'Lme/jellysquid/mods/sodium/client/render/SodiumWorldRenderer;renderTileEntities(Lnet/minecraft/class_4587;Lnet/minecraft/class_4599;Lit/unimi/dsi/fastutil/longs/Long2ObjectMap;Lnet/minecraft/class_4184;F)V' in me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer. Using refmap valkyrienskies-1201-common-refmap.json [PREINJECT Applicator Phase -> valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer from mod valkyrienskies -> Prepare Injections ->  -> redirect$bfh000$valkyrienskies$renderShipChunkBlockEntity(Lnet/minecraft/class_824;Lnet/minecraft/class_2586;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;Lnet/minecraft/class_4587;Lnet/minecraft/class_4599;Lit/unimi/dsi/fastutil/longs/Long2ObjectMap;Lnet/minecraft/class_4184;F)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Redirect annotation on renderShipChunkBlockEntity could not find any targets matching 'Lme/jellysquid/mods/sodium/client/render/SodiumWorldRenderer;renderTileEntities(Lnet/minecraft/class_4587;Lnet/minecraft/class_4599;Lit/unimi/dsi/fastutil/longs/Long2ObjectMap;Lnet/minecraft/class_4184;F)V' in me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer. Using refmap valkyrienskies-1201-common-refmap.json [PREINJECT Applicator Phase -> valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer from mod valkyrienskies -> Prepare Injections ->  -> redirect$bfh000$valkyrienskies$renderShipChunkBlockEntity(Lnet/minecraft/class_824;Lnet/minecraft/class_2586;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;Lnet/minecraft/class_4587;Lnet/minecraft/class_4599;Lit/unimi/dsi/fastutil/longs/Long2ObjectMap;Lnet/minecraft/class_4184;F)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.RedirectInjectionInfo.<init>(RedirectInjectionInfo.java:44) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at jdk.internal.reflect.GeneratedConstructorAccessor64.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_761.handler$bcc000$sodium$init(class_761.java:9468) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.<init>(class_761.java:307) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:583) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[1.20.1-0.15.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]

**Comment by ChristopherJ123** [comment]
Can confirm crash with latest sodium installed

**Comment by mrsterner** [comment]
use sodium 0.4

**Comment by oliverrook** [comment]
Everybody is saying to use sodium 0.4
But on forge, rubidium's 0.4 equivalent
Is incompatible with create/flywheel.

**Comment by oliverrook** [comment]
Not available anymore. Earliest is 6.5
And that was the one that didn't work. Said minimum required was 7.0

**Comment by rjulib00** [comment]
> use rubidium 0.5.6

could u know which version of embeddium is that one?

**Comment by Witherking25** [comment]
For 1.20 there isn't a version of Rubidium/Embeddium that doesn't break shit

**Comment by Rockiecraft** [comment]
valk skies is the only mod incompat with rubidium on 1.20.1 in my pack. i wanted to have working ships but i guess i won't be having them anytime soon.

**Comment by ewoudje** [comment]
Closing in favor of https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/556
