### ISSUE TITLE
Crashes server on forge 1.19.2

### ISSUE THREAD

**Issue by adriankiezik** [ValkyrienSkies/Valkyrien-Skies-2#745]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

Suddenly crashes server

### Issue reproduction

Server running 24/7 crashes 2-4 times a day when mod is included

### Logs

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2024-02-23 18:45:34
Description: Exception in server tick loop

org.valkyrienskies.core.impl.util.assertions.stages.ConstraintFailedException: Constraints failed. Stages since last reset: [PRE_TICK, GET_LAST_TICK_CHANGES, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, POST_TICK_START, POST_TICK_GENERATED, POST_TICK_FINISH, GET_CURRENT_TICK_CHANGES, CLEAR_FOR_RESET, UPDATE_DIMENSIONS, UPDATE_PLAYERS]
Required stages matching predicate in the following order: [PRE_TICK, oneOf[UPDATE_DIMENSIONS, UPDATE_BLOCKS, UPDATE_CHUNKS], POST_TICK_START, POST_TICK_GENERATED, POST_TICK_FINISH, CLEAR_FOR_RESET, UPDATE_PLAYERS]
	at org.valkyrienskies.core.impl.util.assertions.stages.TickStageEnforcerImpl.stage(Unknown Source) ~[valkyrienskies-119-2.1.2-beta.1%20(1).jar%23719!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.game.ships.ShipObjectServerWorld.setPlayers(Unknown Source) ~[valkyrienskies-119-2.1.2-beta.1%20(1).jar%23719!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.handler$bog000$preTick(MinecraftServer.java:6049) ~[server-1.19.2-20220805.130853-srg.jar%23737!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java) ~[server-1.19.2-20220805.130853-srg.jar%23737!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23737!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23737!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 6.1.0-12-amd64
	Java Version: 17.0.10, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 3512467920 bytes (3349 MiB) / 6794772480 bytes (6480 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 12
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 125768.47
	Virtual memory used (MB): 66384.95
	Swap memory total (MB): 61407.00
	Swap memory used (MB): 2683.00
	JVM Flags: 2 total; -Xms128M -Xmx16384M
	Server Running: true

**Comment by Rubydesic** [comment]
Looks like your issue might be caused by the other mods you have installed. Please try to replicate the issue with just VS and addons, and then create a new issue.
