### ISSUE TITLE
<titlI experienced a server crash when using a multi-world plugin to create worlds on the server.e>

### ISSUE THREAD

**Issue by lsz3399747433** [ValkyrienSkies/Valkyrien-Skies-2#763]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

I would like to enjoy this mod with my friends, but the server crashes when creating worlds with the multi-world plugin.

### Issue reproduction

When I send the command 'mv create xxx normal', it causes the server to crash and shut down.

### Logs

[07:33:38 INFO]: RoofClock: Starting creation of world 'zc'...
[07:33:38 INFO]: [Multiverse-Core] Loading World & Settings - 'zc' - Env: NORMAL - Type: NORMAL
[07:33:38 WARN]: org.valkyrienskies.core.impl.util.assertions.stages.ConstraintFailedException: Constraints failed. Stages since last reset: [PRE_TICK, GET_LAST_TICK_CHANGES, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, POST_TICK_START, POST_TICK_GENERATED, POST_TICK_FINISH, GET_CURRENT_TICK_CHANGES, CLEAR_FOR_RESET, UPDATE_DIMENSIONS]
[07:33:38 WARN]: Required stages matching predicate in the following order: [PRE_TICK, oneOf[UPDATE_DIMENSIONS, UPDATE_BLOCKS, UPDATE_CHUNKS], POST_TICK_START, POST_TICK_GENERATED, POST_TICK_FINISH, CLEAR_FOR_RESET, UPDATE_PLAYERS]
[07:33:38 WARN]:        at TRANSFORMER/valkyrienskies@2.1.3-beta.1/org.valkyrienskies.core.impl.util.assertions.stages.TickStageEnforcerImpl.stage(Unknown Source)
[07:33:38 WARN]:        at TRANSFORMER/valkyrienskies@2.1.3-beta.1/org.valkyrienskies.core.impl.game.ships.ShipObjectServerWorld.addDimension(Unknown Source)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.handler$zgd000$onInit(ServerLevel.java:2473)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:319)
[07:33:38 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.craftbukkit.v1_20_R1.CraftServer.createWorld(CraftServer.java:1110)
[07:33:38 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.Bukkit.createWorld(Bukkit.java:705)
[07:33:38 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.WorldCreator.createWorld(WorldCreator.java:406)
[07:33:38 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486)
[07:33:38 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:288)
[07:33:38 WARN]:        at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:125)
[07:33:38 WARN]:        at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296)
[07:33:38 WARN]:        at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
[07:33:38 WARN]:        at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[07:33:38 WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:839)
[07:33:38 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[07:33:38 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147)
[07:33:38 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:885)
[07:33:38 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:51)
[07:33:38 WARN]:        at MC-BOOTSTRAP/brigadier@1.20.1/com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.commands.Commands.m_242674_(Commands.java:318)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerGamePacketListenerImpl.java:1835)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$10(ServerGamePacketListenerImpl.java:1799)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67)
[07:33:38 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1029)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1012)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1006)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:991)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:908)
[07:33:38 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281)
[07:33:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:33:38 ERROR]: [Multiverse-Core] The world 'zc' could NOT be loaded because it contains errors and is probably corrupt!
[07:33:38 ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'zc'
[07:33:38 ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[07:33:38 ERROR]: [Multiverse-Core] Failed to Create/Load the world 'zc'
[07:33:38 INFO]: RoofClock: FAILED.
[07:33:38 ERROR]: Encountered an unexpected exception
org.valkyrienskies.core.impl.util.assertions.stages.ConstraintFailedException: Constraints failed. Stages since last reset: [PRE_TICK, GET_LAST_TICK_CHANGES, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, POST_TICK_START, POST_TICK_GENERATED, POST_TICK_FINISH, GET_CURRENT_TICK_CHANGES, CLEAR_FOR_RESET, UPDATE_DIMENSIONS, UPDATE_PLAYERS]
Required stages matching predicate in the following order: [PRE_TICK, oneOf[UPDATE_DIMENSIONS, UPDATE_BLOCKS, UPDATE_CHUNKS], POST_TICK_START, POST_TICK_GENERATED, POST_TICK_FINISH, CLEAR_FOR_RESET, UPDATE_PLAYERS]
        at org.valkyrienskies.core.impl.util.assertions.stages.TickStageEnforcerImpl.stage(Unknown Source) ~[%5B服务端%5D瓦尔valkyrienskies-120-2.1.3-beta.1.jar%23199!/:?]
        at org.valkyrienskies.core.impl.game.ships.ShipObjectServerWorld.setPlayers(Unknown Source) ~[%5B服务端%5D瓦尔valkyrienskies-120-2.1.3-beta.1.jar%23199!/:?]
        at net.minecraft.server.MinecraftServer.handler$zfm000$preTick(MinecraftServer.java:2849) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:904) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[07:33:38 FATAL]: Preparing crash report with UUID e6cf2c7b-5c0b-4ffd-98e4-edb993592b38

**Comment by thetheaplant** [comment]
Valkyrien skies does not work with plugins. I would suggest using server software that does not include plugins

**Comment by PriestOfFerns** [comment]
Most plugin-mod hybrid servers do some pretty invasive things to get themselves working. Which is why mods like create used to not work with them.

VS2 does a lot of mixin-ing into minecraft’s code to work, so all the invasive stuff said hybrid servers do tends to cause problems with it.
