### ISSUE TITLE
Crash when entering the game, with Sodium and Litematica mods

### ISSUE THREAD

**Issue by pama1234** [ValkyrienSkies/Valkyrien-Skies-2#818]
### Mod Name

Sodium, Litematica

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

The Game crashed.

related issues：
- https://github.com/maruohon/litematica/issues/501

the problem: 
- https://github.com/ValkyrienSkies/Valkyrien-Skies-2/blob/d9e0db7d3354dcd03c4a8a40c3d72ed3ee664cba/common/src/main/java/org/valkyrienskies/mod/mixin/mod_compat/sodium/MixinSodiumWorldRenderer.java#L53

### Issue reproduction

install Sodium, Litematica(and MaLiLib), and Valkyrien-Skies on a 1.20.1 fabric client, create and enter a single player map.

### Logs

java.lang.ClassCastException: class fi.dy.masa.litematica.world.WorldSchematic cannot be cast to class net.minecraft.class_638 (fi.dy.masa.litematica.world.WorldSchematic and net.minecraft.class_638 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @103f852)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$hhg000$valkyrienskies$renderShipBlockEntityInShipyard(SodiumWorldRenderer.java:1572) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:349) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:308) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$hhg000$valkyrienskies$renderShipBlockEntities(SodiumWorldRenderer.java:1598) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:271) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at net.minecraft.class_761.handler$gki000$sodium$onRenderBlockEntities(class_761.java:22098) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1372) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1%20%e6%b5%8b%e8%af%95%e7%94%a8.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]

**Comment by pama1234** [comment]
other related issues: 
- https://github.com/maruohon/litematica/issues/737
- https://github.com/maruohon/litematica/issues/830

if any rendering problems occurred such as:
- entity and block entity malposition
- ship disappear

and you want to use litematica with valkyrien skies, disable schematic rendering in Litematica config while you're not using it. (https://github.com/maruohon/litematica/issues/737#issuecomment-1638813641)

**Comment by MeditatorLogic** [comment]
ha it seems that the problem has been widely reported.
**### P.S. if schem mods may really be compatable with vs2 engine, the thing should be that making every mass of vanila blocks less like 1/100 before or it will be impossible to fly anything as large as a spaceship with engines in like tournament or kontarption.**

**Comment by PriestOfFerns** [comment]
@MeditatorLogic people have already flown large ships with current mass values, i don’t think vs2 devs need to make every single block weigh 100 times less

**Comment by thetheaplant** [comment]
Fixed in #819
