### ISSUE TITLE
<title>Server crashes

### ISSUE THREAD

**Issue by lava114514** [ValkyrienSkies/Valkyrien-Skies-2#824]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

Server crashes with Valkyrien Skies

### Issue reproduction

1.install latest forge server
2.put "valkyrienskies-120-2.3.0-beta.5.jar" and "kotlinforforge-4.10.0-all.jar" into mods
3.launch server and it crashes 

### Logs

Time: 2024-04-27 13:20:57
Description: Exception in server tick loop

java.lang.UnsatisfiedLinkError: 'long org.valkyrienskies.physics_api_krunch.KrunchByteBuffer.getDirectBufferAddress(java.nio.ByteBuffer)'
	at org.valkyrienskies.physics_api_krunch.KrunchByteBuffer.getDirectBufferAddress(Native Method) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.physics_api_krunch.KrunchByteBuffer.<init>(KrunchByteBuffer.java:16) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.physics_api_krunch.factories.KrunchByteBufferFactory.createVSByteBuffer(VSKrunchPhysicsFactories.kt:23) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.physics_api_krunch.factories.KrunchByteBufferFactory.createVSByteBuffer(VSKrunchPhysicsFactories.kt:22) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.Aq.<init>(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.Ar.a(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.Ar.a(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.Ar.get(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.Au.a(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.Au.get(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.bz.get(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.program.DaggerVSCoreServerFactory$VSPipelineComponentImpl.newPipeline(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.program.VSCoreImpl.fromModule(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.program.VSCoreImpl.newPipeline(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.program.VSCoreServerImpl.newPipeline(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:classloading}
	at org.valkyrienskies.mod.common.ShipSavedData$Companion.createEmpty(ShipSavedData.java:21) ~[valkyrienskies-120-2.3.0-beta.5.jar%23103!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164861_(DimensionDataStorage.java:43) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.handler$zbp000$postCreateLevels(MinecraftServer.java:1939) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:339) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:308) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:164) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (aarch64) version 5.10.136-android12-9-00004-ga5de78edc8e6-ab9756862
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1181289280 bytes (1126 MiB) / 1488977920 bytes (1420 MiB) up to 2919235584 bytes (2784 MiB)
	CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	JVM Flags: 0 total; 
	Server Running: true
	Player Count: 0 / 20; []
	Data Packs: vanilla, mod:kotlinforforge (incompatible), mod:mixinextras (incompatible), mod:valkyrienskies (incompatible), mod:cloth_config (incompatible), mod:forge
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.30.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.30.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.30.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.30.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.30.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@4.10.0
		lowcodefml@null
	Mod List: 
		server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: NOSIGNATURE
		kffmod-4.10.0.jar                                 |Kotlin For Forge              |kotlinforforge                |4.10.0              |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0.jar                       |MixinExtras                   |mixinextras                   |0.2.0               |DONE      |Manifest: NOSIGNATURE
		valkyrienskies-120-2.3.0-beta.5.jar               |Valkyrien Skies 2             |valkyrienskies                |2.3.0-beta.5        |DONE      |Manifest: NOSIGNATURE
		cloth-config-forge-11.1.106.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.106            |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.30-universal.jar                |Forge                         |forge                         |47.2.30             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
	Crash Report UUID: e80788d2-722d-4341-9c8c-9bee54612e0b
	FML: 47.2
	Forge: net.minecraftforge:47.2.30

**Comment by super-15** [comment]
It was solved in [946](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/946)
