### ISSUE TITLE
1.20.1 fabric/quilt crashes on start up if Nvidium is installed.

### ISSUE THREAD

**Issue by Unionegation** [ValkyrienSkies/Valkyrien-Skies-2#838]
### Mod Name

Nvidium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Quilt

### Issue description

It happens on both quilt and fabric. When it starts, you are greeted by an error message that just says they're incompatibl.

### Issue reproduction

Install Quilt/Fabric loader, any versions of VS and eureka, and sosium+Nvidium.

### Logs

[12:29:22] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[12:29:22] [main/WARN]: Mod resolution failed
[12:29:22] [main/INFO]: Immediate reason: [NEG_HARD_DEP valkyrienskies 2.3.0-beta.5 {breaks nvidium @ [*]}, ROOT_FORCELOAD_SINGLE nvidium 0.2.6-beta, ROOT_FORCELOAD_SINGLE valkyrienskies 2.3.0-beta.5]
[12:29:22] [main/INFO]: Reason: [NEG_HARD_DEP valkyrienskies 2.3.0-beta.5 {breaks nvidium @ [*]}]
[12:29:22] [main/INFO]: Fix: add [], remove [], replace [[valkyrienskies 2.3.0-beta.5] -> add:valkyrienskies 2.1.3-beta.1 ([[2.1.3-beta.1,?)])]
[12:29:22] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Valkyrien Skies 2' (valkyrienskies) 2.3.0-beta.5 with version 2.1.3-beta.1 or later that is compatible with:
		 - nvidium 0.2.6-beta
More details:
	 - Mod 'Valkyrien Skies 2' (valkyrienskies) 2.3.0-beta.5 is incompatible with any version of mod 'Nvidium' (nvidium), but a matching version is present: 0.2.6-beta!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]

**Comment by TimSousa1** [comment]
yep, I'm having the same issue. I thought the mods were compatible? nvidium seems to be missing from their [incompatibility list](https://wiki.valkyrienskies.org/wiki/Compatibility_list)..
My error report doesn't even recommend a previous version of VS: 
```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Valkyrien Skies 2' (valkyrienskies) 2.3.0-beta.5 with version 2.3.0-beta.5 or later that is compatible with:
		 - nvidium 0.2.6-beta
More details:
	 - Mod 'Valkyrien Skies 2' (valkyrienskies) 2.3.0-beta.5 is incompatible with any version of mod 'Nvidium' (nvidium), but a matching version is present: 0.2.6-beta!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by thetheaplant** [comment]
Nvidium is compatible, the wiki incompatibility list is not up to date.
