### ISSUE TITLE
VS and Nvidium not compatible

### ISSUE THREAD

**Issue by elliothawkz2** [ValkyrienSkies/Valkyrien-Skies-2#888]
### Mod Name

Nvidium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

Starting minecraft up and Fabric displays an error message, saying VS is not compatible with any version of Nvidium.

### Issue reproduction

Install Minecraft 1.20.1
Install Fabric Mod Loader
Install VS
Install Sodium
Install Nvidium
Start the game

### Logs

[21:46:22] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[21:46:22] [main/WARN]: Mod resolution failed
[21:46:22] [main/INFO]: Immediate reason: [NEG_HARD_DEP valkyrienskies 2.3.0-beta.5 {breaks nvidium @ [*]}, ROOT_FORCELOAD_SINGLE nvidium 0.2.6-beta, ROOT_FORCELOAD_SINGLE valkyrienskies 2.3.0-beta.5]
[21:46:22] [main/INFO]: Reason: [NEG_HARD_DEP valkyrienskies 2.3.0-beta.5 {breaks nvidium @ [*]}]
[21:46:22] [main/INFO]: Fix: add [], remove [], replace [[valkyrienskies 2.3.0-beta.5] -> add:valkyrienskies 1 ([(-âˆ,âˆ)])]
[21:46:22] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Valkyrien Skies 2' (valkyrienskies) 2.3.0-beta.5 with any version that is compatible with:
		 - nvidium 0.2.6-beta
More details:
	 - Mod 'Valkyrien Skies 2' (valkyrienskies) 2.3.0-beta.5 is incompatible with any version of mod 'Nvidium' (nvidium), but a matching version is present: 0.2.6-beta!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) ~[?:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) ~[?:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) ~[?:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) ~[?:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) ~[?:?]
Process exited with code 1.
Clipboard copy at: 02 Jul 2024 21:48:01 +0700

**Comment by thetheaplant** [comment]
Known issue, likely needs to be fixed by Nvidium.

**Comment by Maksiu8226** [comment]
i have same problem, i need fix for this

**Comment by TheAwesome98-Real** [comment]
> Fabric displays an error message, saying VS is not compatible with any version of Nvidium.

yeah, this is intended, so you can't launch the game when nvidium is installed. you probably have to wait until nvidium fixes a bug before that can be removed

**Comment by thetheaplant** [comment]
A fixed version of nvidium was made, you can find it [here](https://cdn.discordapp.com/attachments/662249805430390795/1287535682335674398/nvidium-0.3.0.jar?ex=66f1e68b&is=66f0950b&hm=772a586eb2b8279c8eb05c5e0c6c8b7ddb03cd0578c09b250fc93e6d0528aa1d&).

**Comment by Qendolin** [comment]
For me when I disassemble ships using this patched version, the model of the ship remains in the world. Reloading chunks with F3+A makes it disappear as it should.

**Comment by TheAwesome98-Real** [comment]
> For me when I disassemble ships using this patched version, the model of the ship remains in the world. Reloading chunks with F3+A makes it disappear as it should.

i think this is another issue and you should open one

**Comment by Bocaj07** [comment]
> A fixed version of nvidium was made, you can find it [here](https://discord.com/channels/244934352092397568/662249805430390795/1287535683023405178).

Hello there, it appears the link you provided no longer works. Could you please update it? I need Nvidium cause of my 16th century potato PC screams at me in flames when i try VS without it

**Comment by thetheaplant** [comment]
@Bocaj07  https://cdn.rubydesic.com/1mZXtH3De/valkyrienskies-120-2.3.0-beta.5.jar

**Comment by TungstenWolf** [comment]
> [@Bocaj07](https://github.com/Bocaj07) [cdn.rubydesic.com/1mZXtH3De/valkyrienskies-120-2.3.0-beta.5.jar](https://cdn.rubydesic.com/1mZXtH3De/valkyrienskies-120-2.3.0-beta.5.jar)

Thats not the same file? You provided a link to valkyiren skies despit looking for the fixed version of nvidium
