### ISSUE TITLE
Crash when enable rendering schematics by forgematica and embeddium render

### ISSUE THREAD

**Issue by WANGNIMA912** [ValkyrienSkies/Valkyrien-Skies-2#914]
### Mod Name

forgematica,embeddium

### This issue occurs when only Valkyrien Skies, addons, and the mod I have specified are installed and no other mods

- [X] I have tested this issue and it occurs with only Valkyrien Skies, addons, and the mod I have specified

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

when i enabling all render, the client shut down

### Issue reproduction

1.20.1 Forge, create a physics object at first, then press m+r to enable forgmatica render, then the world will shutdown

### Logs

[debug.log](https://github.com/user-attachments/files/16330944/debug.log)
[latest.log](https://github.com/user-attachments/files/16330945/latest.log)

**Comment by WANGNIMA912** [comment]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-07-22 17:22:41
Description: Unexpected error

java.lang.ClassCastException: class fi.dy.masa.litematica.world.WorldSchematic cannot be cast to class net.minecraft.client.multiplayer.ClientLevel (fi.dy.masa.litematica.world.WorldSchematic is in module forgematica@0.1.5-mc1.20.1 of loader 'TRANSFORMER' @31973858; net.minecraft.client.multiplayer.ClientLevel is in module minecraft@1.20.1 of loader 'TRANSFORMER' @31973858)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$zfo000$renderShipBlockEntityInShipyard(SodiumWorldRenderer.java:771) ~[embeddium-0.3.25+mc1.20.1.jar%23161!/:?] {re:mixin,re:classloading,pl:mixin:APP:valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:505) ~[embeddium-0.3.25+mc1.20.1.jar%23161!/:?] {re:mixin,re:classloading,pl:mixin:APP:valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:457) ~[embeddium-0.3.25+mc1.20.1.jar%23161!/:?] {re:mixin,re:classloading,pl:mixin:APP:valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$zfo000$renderShipBlockEntities(SodiumWorldRenderer.java:797) ~[embeddium-0.3.25+mc1.20.1.jar%23161!/:?] {re:mixin,re:classloading,pl:mixin:APP:valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:413) ~[embeddium-0.3.25+mc1.20.1.jar%23161!/:?] {re:mixin,re:classloading,pl:mixin:APP:valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer,pl:mixin:A}
	at net.minecraft.client.renderer.LevelRenderer.handler$zii000$onRenderBlockEntities(LevelRenderer.java:8295) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin,pl:mixin:APP:mafglib.mixins.json:MixinWorldRenderer,pl:mixin:APP:forgematica.mixins.json:MixinWorldRenderer,pl:mixin:APP:valkyrienskies-common.mixins.json:accessors.client.render.LevelRendererAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinLevelRenderer,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.transform_particles.MixinLevelRenderer,pl:mixin:APP:valkyrienskies-forge.mixins.json:client.render.MixinLevelRenderer,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1268) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin,pl:mixin:APP:mafglib.mixins.json:MixinWorldRenderer,pl:mixin:APP:forgematica.mixins.json:MixinWorldRenderer,pl:mixin:APP:valkyrienskies-common.mixins.json:accessors.client.render.LevelRendererAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinLevelRenderer,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.transform_particles.MixinLevelRenderer,pl:mixin:APP:valkyrienskies-forge.mixins.json:client.render.MixinLevelRenderer,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinGameRenderer,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinGameRenderer,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mafglib.mixins.json:MixinMinecraftClient,pl:mixin:APP:forgematica.mixins.json:MixinMinecraftClient,pl:mixin:APP:valkyrienskies-common.mixins.json:client.MixinMinecraft,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mafglib.mixins.json:MixinMinecraftClient,pl:mixin:APP:forgematica.mixins.json:MixinMinecraftClient,pl:mixin:APP:valkyrienskies-common.mixins.json:client.MixinMinecraft,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[maticacompat.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.5.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.5.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	Embeddium (embeddium), Version: 0.3.25+mc1.20.1
		at TRANSFORMER/embeddium@0.3.25+mc1.20.1/me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$zfo000$renderShipBlockEntityInShipyard(SodiumWorldRenderer.java:771)

	Valkyrien Skies 2 (valkyrienskies), Version: 2.3.0-beta.5
		Issue tracker URL: https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues
		Mixin class: org.valkyrienskies.mod.mixin.mod_compat.sodium.MixinSodiumWorldRenderer
		Target: me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer
		at TRANSFORMER/embeddium@0.3.25+mc1.20.1/me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$zfo000$renderShipBlockEntityInShipyard(SodiumWorldRenderer.java:771)
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$zfo000$renderShipBlockEntityInShipyard(SodiumWorldRenderer.java:771) ~[embeddium-0.3.25+mc1.20.1.jar%23161!/:?] {re:mixin,re:classloading,pl:mixin:APP:valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:505) ~[embeddium-0.3.25+mc1.20.1.jar%23161!/:?] {re:mixin,re:classloading,pl:mixin:APP:valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:457) ~[embeddium-0.3.25+mc1.20.1.jar%23161!/:?] {re:mixin,re:classloading,pl:mixin:APP:valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$zfo000$renderShipBlockEntities(SodiumWorldRenderer.java:797) ~[embeddium-0.3.25+mc1.20.1.jar%23161!/:?] {re:mixin,re:classloading,pl:mixin:APP:valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:413) ~[embeddium-0.3.25+mc1.20.1.jar%23161!/:?] {re:mixin,re:classloading,pl:mixin:APP:valkyrienskies-common.mixins.json:mod_compat.sodium.MixinSodiumWorldRenderer,pl:mixin:A}
	at net.minecraft.client.renderer.LevelRenderer.handler$zii000$onRenderBlockEntities(LevelRenderer.java:8295) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin,pl:mixin:APP:mafglib.mixins.json:MixinWorldRenderer,pl:mixin:APP:forgematica.mixins.json:MixinWorldRenderer,pl:mixin:APP:valkyrienskies-common.mixins.json:accessors.client.render.LevelRendererAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinLevelRenderer,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.transform_particles.MixinLevelRenderer,pl:mixin:APP:valkyrienskies-forge.mixins.json:client.render.MixinLevelRenderer,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1268) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin,pl:mixin:APP:mafglib.mixins.json:MixinWorldRenderer,pl:mixin:APP:forgematica.mixins.json:MixinWorldRenderer,pl:mixin:APP:valkyrienskies-common.mixins.json:accessors.client.render.LevelRendererAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinLevelRenderer,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.transform_particles.MixinLevelRenderer,pl:mixin:APP:valkyrienskies-forge.mixins.json:client.render.MixinLevelRenderer,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinGameRenderer,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Mojang_and_bug'/41, l='ClientLevel', x=13.83, y=-53.87, z=26.45]]
	Chunk stats: 961, 663
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 3310 game time, 3310 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:embeddium.mixins.json:features.render.world.ClientLevelMixin,pl:mixin:APP:forgematica.mixins.json:MixinClientWorld,pl:mixin:APP:valkyrienskies-common.mixins.json:accessors.client.multiplayer.ClientLevelAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:client.world.MixinClientLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.block_tint.MixinClientLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.shipyard_entities.MixinClientLevel,pl:mixin:APP:embeddium.mixins.json:core.world.biome.ClientWorldMixin,pl:mixin:APP:embeddium.mixins.json:core.world.map.ClientWorldMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.ClientWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mafglib.mixins.json:MixinMinecraftClient,pl:mixin:APP:forgematica.mixins.json:MixinMinecraftClient,pl:mixin:APP:valkyrienskies-common.mixins.json:client.MixinMinecraft,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mafglib.mixins.json:MixinMinecraftClient,pl:mixin:APP:forgematica.mixins.json:MixinMinecraftClient,pl:mixin:APP:valkyrienskies-common.mixins.json:client.MixinMinecraft,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[maticacompat.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.5.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.5.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 929038336 bytes (886 MiB) / 2659188736 bytes (2536 MiB) up to 8053063680 bytes (7680 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.41
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1c81
	Graphics card #0 versionInfo: DriverVersion=32.0.15.6070
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 32617.65
	Virtual memory used (MB): 12994.14
	Swap memory total (MB): 16308.82
	Swap memory used (MB): 20.26
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn1152m -Xmx7680m
	Launched Version: maticacompat
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 560.70, NVIDIA Corporation
	Window size: 1643x874
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: zh_cn
	CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Mojang_and_bug'/41, l='ServerLevel[新的世界]', x=13.83, y=-53.87, z=26.45]]
	Data Packs: vanilla, mod:mafglib, mod:kotlinforforge (incompatible), mod:forgematica (incompatible), mod:mixinextras (incompatible), mod:valkyrienskies (incompatible), mod:cloth_config (incompatible), mod:forge, mod:embeddium
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		kotlinforforge@4.11.0
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		MaFgLib-0.1.11-mc1.20.1.jar                       |MaFgLib                       |mafglib                       |0.1.11-mc1.20.1     |DONE      |Manifest: NOSIGNATURE
		kffmod-4.11.0.jar                                 |Kotlin For Forge              |kotlinforforge                |4.11.0              |DONE      |Manifest: NOSIGNATURE
		Forgematica-0.1.5-mc1.20.1.jar                    |Forgematica                   |forgematica                   |0.1.5-mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |DONE      |Manifest: NOSIGNATURE
		valkyrienskies-120-2.3.0-beta.5.jar               |Valkyrien Skies 2             |valkyrienskies                |2.3.0-beta.5        |DONE      |Manifest: NOSIGNATURE
		cloth-config-forge-11.1.106.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.106            |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.3.5-universal.jar                 |Forge                         |forge                         |47.3.5              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		embeddium-0.3.25+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.3.25+mc1.20.1     |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: e90040a1-dd96-4885-bee1-08d153d6e993
	FML: 47.3
	Forge: net.minecraftforge:47.3.5

**Comment by thetheaplant** [comment]
Closing in favor of #906
