### ISSUE TITLE
Whenever I try to load a world with Valkyrien Skies installed, it displays this error. Yes I have koltin installed.

### ISSUE THREAD

**Issue by RedHood866** [ValkyrienSkies/Valkyrien-Skies-2#931]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

I have tried installing two different versions of the mod, with the same issue still applying.

It displays this error message when I load a world:

org.valkyrienskies.physics_api_krunch.KrunchByteBuffer.getDirectBufferAddress(java.nio.ByteBuffer)'

### Issue reproduction

It happens whenever I load a world with just valkyrien skies (and koltin) installed.

### Logs

---- Minecraft Crash Report ----
// Sorry :(

Time: 2024-08-02 01:46:26
Description: Exception in server tick loop

java.lang.UnsatisfiedLinkError: 'long org.valkyrienskies.physics_api_krunch.KrunchByteBuffer.getDirectBufferAddress(java.nio.ByteBuffer)'
	at org.valkyrienskies.physics_api_krunch.KrunchByteBuffer.getDirectBufferAddress(Native Method) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:classloading}
	at org.valkyrienskies.physics_api_krunch.KrunchByteBuffer.<init>(KrunchByteBuffer.java:16) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:classloading}
	at org.valkyrienskies.physics_api_krunch.factories.KrunchByteBufferFactory.createVSByteBuffer(VSKrunchPhysicsFactories.kt:23) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:classloading}
	at org.valkyrienskies.physics_api_krunch.factories.KrunchByteBufferFactory.createVSByteBuffer(VSKrunchPhysicsFactories.kt:22) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.Aq.<init>(Unknown Source) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.Ar.a(Unknown Source) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.Ar.a(Unknown Source) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.Ar.get(Unknown Source) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.Au.a(Unknown Source) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.Au.get(Unknown Source) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.shadow.bz.get(Unknown Source) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.program.DaggerVSCoreClientFactory$VSPipelineComponentImpl.newPipeline(Unknown Source) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.program.VSCoreImpl.fromModule(Unknown Source) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.program.VSCoreImpl.newPipeline(Unknown Source) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:classloading}
	at org.valkyrienskies.core.impl.program.VSCoreClientImpl.newPipeline(Unknown Source) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:classloading}
	at org.valkyrienskies.mod.common.ShipSavedData$Companion.createEmpty(ShipSavedData.java:21) ~[valkyrienskies-120-2.1.3-beta.1.jar%23154!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164861_(DimensionDataStorage.java:43) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.handler$zbp000$postCreateLevels(MinecraftServer.java:1939) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:339) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:308) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:63) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Mac OS X (x86_64) version 10.15.7
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 628365952 bytes (599 MiB) / 1241513984 bytes (1184 MiB) up to 7516192768 bytes (7168 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GT 750M
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x0fe9
	Graphics card #0 versionInfo: Revision ID: 0x00a2, ROM Revision: 3762
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 17408.00
	Virtual memory used (MB): 10761.13
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 154.25
	JVM Flags: 8 total; -Xss1M -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:forge, mod:kotlinforforge (incompatible), mod:mixinextras (incompatible), mod:valkyrienskies (incompatible), mod:cloth_config (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.20.1-forge-47.2.0
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@4.3.0
		lowcodefml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		kffmod-4.3.0.jar                                  |Kotlin For Forge              |kotlinforforge                |4.3.0               |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0.jar                       |MixinExtras                   |mixinextras                   |0.2.0               |DONE      |Manifest: NOSIGNATURE
		valkyrienskies-120-2.1.3-beta.1.jar               |Valkyrien Skies 2             |valkyrienskies                |2.1.3-beta.1        |DONE      |Manifest: NOSIGNATURE
		cloth-config-forge-11.1.106.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.106            |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
	Crash Report UUID: f4d6c600-8b3d-42f3-bb5a-cddb94dbc382
	FML: 47.2
	Forge: net.minecraftforge:47.2.0

**Comment by thetheaplant** [comment]
Hello, your version of macOS does not appear to support ByteBuffering, which the physics engine uses to get direct access to ram addresses. Consider upgrading to Windows or Linux.

**Comment by RedHood866** [comment]
Man that suckssss
