### ISSUE TITLE
VS Server Crash

### ISSUE THREAD

**Issue by Alpakakaka** [ValkyrienSkies/Valkyrien-Skies-2#946]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

The server crashes upon starting.

### Issue reproduction

installed Forge with Valkyrian Skies 1.20.1 on a server

### Logs

`[16:18:32] [Server thread/ERROR] [VSCore/]: Failed to load Krunch binary!
java.lang.RuntimeException: Couldn't load shared library 'libKrunchJni64.so' for target: Linux, 64-bit
        at org.valkyrienskies.physics_api_krunch.shared_library_loader.KrunchPhysicsAPISharedLibraryLoader.load(KrunchPhysicsAPISharedLibraryLoader.java:111) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.physics_api_krunch.KrunchBootstrap.loadNativeBinaries(KrunchBootstrap.kt:32) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.core.impl.program.VSCoreImpl.fromModule(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.core.impl.program.VSCoreImpl.newPipeline(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.core.impl.program.VSCoreServerImpl.newPipeline(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.mod.common.ShipSavedData$Companion.load(ShipSavedData.java:35) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:mixin,re:classloading}
        at org.valkyrienskies.mod.common.ShipSavedData.load(ShipSavedData.java) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.level.storage.DimensionDataStorage.m_164868_(DimensionDataStorage.java:70) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
        at net.minecraft.world.level.storage.DimensionDataStorage.m_164858_(DimensionDataStorage.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
        at net.minecraft.world.level.storage.DimensionDataStorage.m_164861_(DimensionDataStorage.java:39) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
        at net.minecraft.server.MinecraftServer.handler$bek000$valkyrienskies$postCreateLevels(MinecraftServer.java:4439) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:339) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:308) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:164) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:connector_pre_launch:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A}
        at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: /tmp/libgdx?/12cf652/libKrunchJni64.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/libgdx?/12cf652/libKrunchJni64.so)
        at org.valkyrienskies.physics_api_krunch.shared_library_loader.KrunchPhysicsAPISharedLibraryLoader.loadFile(KrunchPhysicsAPISharedLibraryLoader.java:307) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.physics_api_krunch.shared_library_loader.KrunchPhysicsAPISharedLibraryLoader.load(KrunchPhysicsAPISharedLibraryLoader.java:107) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        ... 16 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libgdx?/12cf652/libKrunchJni64.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/libgdx?/12cf652/libKrunchJni64.so)
        at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?] {}
        at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331) ~[?:?] {}
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197) ~[?:?] {}
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139) ~[?:?] {}
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418) ~[?:?] {}
        at java.lang.Runtime.load0(Runtime.java:852) ~[?:?] {}
        at java.lang.System.load(System.java:2025) ~[?:?] {re:mixin}
        at org.valkyrienskies.physics_api_krunch.shared_library_loader.KrunchPhysicsAPISharedLibraryLoader.loadFile(KrunchPhysicsAPISharedLibraryLoader.java:313) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.physics_api_krunch.shared_library_loader.KrunchPhysicsAPISharedLibraryLoader.loadFile(KrunchPhysicsAPISharedLibraryLoader.java:282) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.physics_api_krunch.shared_library_loader.KrunchPhysicsAPISharedLibraryLoader.load(KrunchPhysicsAPISharedLibraryLoader.java:107) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        ... 16 more
[16:18:32] [Server thread/INFO] [or.va.co.im.ne.VSNetworking/]: We are not using UDP, falling back to TCP
[16:18:32] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.UnsatisfiedLinkError: 'long org.valkyrienskies.physics_api_krunch.KrunchByteBuffer.getDirectBufferAddress(java.nio.ByteBuffer)'
        at org.valkyrienskies.physics_api_krunch.KrunchByteBuffer.getDirectBufferAddress(Native Method) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.physics_api_krunch.KrunchByteBuffer.<init>(KrunchByteBuffer.java:16) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.physics_api_krunch.factories.KrunchByteBufferFactory.createVSByteBuffer(VSKrunchPhysicsFactories.kt:23) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.physics_api_krunch.factories.KrunchByteBufferFactory.createVSByteBuffer(VSKrunchPhysicsFactories.kt:22) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.core.impl.shadow.Aq.<init>(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.core.impl.shadow.Ar.a(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.core.impl.shadow.Ar.a(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.core.impl.shadow.Ar.get(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.core.impl.shadow.Au.a(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.core.impl.shadow.Au.get(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.core.impl.shadow.bz.get(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.core.impl.program.DaggerVSCoreServerFactory$VSPipelineComponentImpl.newPipeline(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.core.impl.program.VSCoreImpl.fromModule(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.core.impl.program.VSCoreImpl.newPipeline(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.core.impl.program.VSCoreServerImpl.newPipeline(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:classloading}
        at org.valkyrienskies.mod.common.ShipSavedData$Companion.load(ShipSavedData.java:35) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:mixin,re:classloading}
        at org.valkyrienskies.mod.common.ShipSavedData.load(ShipSavedData.java) ~[valkyrienskies-120-2.3.0-beta.5.jar%23371!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.level.storage.DimensionDataStorage.m_164868_(DimensionDataStorage.java:70) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
        at net.minecraft.world.level.storage.DimensionDataStorage.m_164858_(DimensionDataStorage.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
        at net.minecraft.world.level.storage.DimensionDataStorage.m_164861_(DimensionDataStorage.java:39) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
        at net.minecraft.server.MinecraftServer.handler$bek000$valkyrienskies$postCreateLevels(MinecraftServer.java:4439) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:339) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:308) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:164) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:connector_pre_launch:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A}
        at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}
[16:18:32] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 9efac77c-83ae-4359-836d-184249cc2ffd
[16:18:32] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/container/./crash-reports/crash-2024-08-22_16.18.32-server.txt
[16:18:32] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "org.valkyrienskies.core.apigame.world.ServerShipWorldCore.setGameServer(org.valkyrienskies.core.apigame.GameServer)" because "this.shipWorld" is null
        at net.minecraft.server.MinecraftServer.handler$bek000$valkyrienskies$preStopServer(MinecraftServer.java:4688) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_7041_(DedicatedServer.java:510) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:connector_pre_launch:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A,pl:connector_pre_launch:A}
        at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}`

**Comment by thetheaplant** [comment]
Is this a server host or self-hosted?

**Comment by Alpakakaka** [comment]
Server is hosted via a providern, not self-hosted

**Comment by thetheaplant** [comment]
Your provider does not support vs2's physics library, consider using another host.

**Comment by Alpakakaka** [comment]
Is there anything I could ask the provider to do? What's the issue exactly?
