### ISSUE TITLE
<title>1.20.1 beta-6 version addon error.

### ISSUE THREAD

**Issue by REFIRSER2** [ValkyrienSkies/Valkyrien-Skies-2#960]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

if load valkyrian 1.20.1 beta-6 version then cause error.

### Issue reproduction

beta-6 error.

### Logs

-- Head --
Thread: Render thread
Suspected Mod: 
	VS Eureka Mod (vs_eureka), Version: 1.5.1-beta.3
		Issue tracker URL: https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues
		at TRANSFORMER/vs_eureka@1.5.1-beta.3/org.valkyrienskies.eureka.EurekaBlocks.register(EurekaBlocks.java:173)
Stacktrace:
	at org.valkyrienskies.eureka.EurekaBlocks.register(EurekaBlocks.java:173) ~[eureka-1201-1.5.1-beta.3.jar%23198!/:?] {re:classloading}
-- MOD vs_eureka --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:64) ~[kfflang-4.11.0.jar%23270!/:4.11.0] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23213!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/User/curseforge/minecraft/Instances/minecraft 1.20.1 terrapack/mods/eureka-1201-1.5.1-beta.3.jar
	Failure message: VS Eureka Mod (vs_eureka) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.5.1-beta.3
	Mod Issue URL: https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues
	Exception message: java.lang.NoSuchMethodError: 'org.valkyrienskies.core.impl.util.events.EventEmitterImpl org.valkyrienskies.mod.common.hooks.VSGameEvents.getRegistriesCompleted()'
Stacktrace:
	at org.valkyrienskies.eureka.EurekaBlocks.register(EurekaBlocks.java:173) ~[eureka-1201-1.5.1-beta.3.jar%23198!/:?] {re:classloading}
	at org.valkyrienskies.eureka.EurekaMod.init(EurekaMod.java:10) ~[eureka-1201-1.5.1-beta.3.jar%23198!/:?] {re:classloading}
	at org.valkyrienskies.eureka.forge.EurekaModForge.<init>(EurekaModForge.kt:40) ~[eureka-1201-1.5.1-beta.3.jar%23198!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:64) ~[kfflang-4.11.0.jar%23270!/:4.11.0] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23213!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by thetheaplant** [comment]
Eureka does not support beta.6, this is one for the eureka github.
